project_id = "ukcgntxgjltszsgvemxi"

[functions.send-booking-confirmation]
verify_jwt = false

[functions.seed-test-agent-logins]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
