import type { PropertyFlowConfig } from "@/engines/types";

const AGRICULTURE_TYPES = [
  "Agricultural Land",
  "Farm Land",
  "Organic Farm",
  "Mango Farm",
  "Coconut Farm",
  "Palm Oil Farm",
  "Poultry Farm",
  "Dairy Farm",
  "Fish Farm",
  "Greenhouse Farm",
  "Polyhouse Farm",
  "Plantation Land",
  "Horticulture Land",
  "Orchard",
  "Mixed Crop Farm",
  "Open Farm Land",
];

const LAND_UNITS = ["Sq Ft", "Sq Yard", "Cent", "Gunta", "Acre", "Bigha"];

export const agriculturalFlow: PropertyFlowConfig = {
  id: "agricultural_land",

  category: "agriculture",

  label: "Agricultural Lands",

  version: "v2-client-aligned-agriculture",

  engine: {
    mode: "dynamic_conversation",

    strictVisibilityResolution: true,

    dynamicQuestionResolver: true,

    reevaluateOnEveryAnswer: true,

    skipHiddenQuestions: true,

    clearHiddenFieldValues: true,

    preventDuplicateQuestions: true,

    removeIrrelevantQuestions: true,

    conversationMemory: true,

    smartConditionalFlow: true,

    supportContextualQuestions: true,

    supportAIExtraction: true,

    supportNaturalCorrections: true,

    supportConversationalAI: true,

    autoRevalidateDependencies: true,

    dynamicSectionActivation: true,

    clonePropertySupport: true,

    multiVariantSupport: true,

    preserveParentDataDuringClone: true,

    AIBasedNextQuestionSelection: true,

    progressiveConversationMode: true,

    intelligentDependencyRouting: true,

    contextualSkipLogic: true,

    askOnlyContextualQuestions: true,

    propertyTypeAwareQuestions: true,

    dynamicFlowReordering: true,
  },

  ai: {
    enabled: true,

    askOneQuestionAtATime: true,

    askOnlyRelevantQuestions: true,

    askOnlyMissingFields: true,

    supportGreetings: true,

    supportNaturalLanguage: true,

    supportCorrections: true,

    supportSkipIntent: true,

    supportIntentDetection: true,

    supportContextAwareness: true,

    supportConversationalMemory: true,

    supportDocumentExtraction: true,

    supportImageExtraction: true,

    supportAutoFill: true,

    supportDynamicFollowups: true,

    supportPriceCalculation: true,

    supportSmartSuggestions: true,

    supportHumanReplies: true,

    autoGenerateDescription: true,

    autoGenerateTitle: true,

    autoGenerateSEO: true,

    supportVariantDetection: true,

    supportOptionalSectionSkipping: true,
  },

  sections: [
    {
      id: "basic_information",
      label: "Basic Information",
      priority: 1,
    },

    {
      id: "land_configuration",
      label: "Land Configuration",
      priority: 2,
    },

    {
      id: "agriculture_details",
      label: "Agriculture Details",
      priority: 3,
    },

    {
      id: "pricing",
      label: "Pricing",
      priority: 5,
    },

    {
      id: "legal",
      label: "Legal & Payment",
      priority: 6,
    },

    {
      id: "location",
      label: "Location",
      priority: 4,
    },

    {
      id: "finalization",
      label: "Finalization",
      priority: 7,
    },
  ],

  fields: {
    agricultural_land_type: {
      section: "basic_information",

      priority: 1,

      type: "multi_select",

      required: true,

      question: "What type of agricultural land is this?",

      options: AGRICULTURE_TYPES,
    },

    listed_by: {
      section: "basic_information",

      priority: 2,

      type: "single_select",

      required: true,

      question: "Who is listing this property?",

      options: ["Owner", "Agent", "Developer"],
    },

    listing_type: {
      section: "basic_information",

      priority: 3,

      type: "single_select",

      required: true,

      question: "Is this property available for Buy, Lease, Rent or Partnership?",

      options: ["Buy", "Lease", "Rent", "Partnership"],

      invalidateOnChange: ["total_price", "price_per_unit", "rent_amount", "partnership_details"],
    },

    land_area: {
      section: "land_configuration",

      priority: 4,

      type: "measurement",

      required: true,

      requiredIfVisible: true,

      question: "What is the land area?",

      units: LAND_UNITS,

      aiFollowup: {
        triggerAfterAnswer: true,

        askForVariants: true,

        followupQuestion: "Do you have additional land sizes available?",
      },
    },

    land_variants: {
      section: "land_configuration",

      priority: 5,

      type: "multi_variant_group",

      required: false,

      visibleIf: {
        field: "add_multiple_land_sizes",
        equals: "Yes",
      },

      question: "Add all available agricultural land size variants.",

      cloneStrategy: {
        enabled: true,

        preserveFields: [
          "agricultural_land_type",
          "listed_by",
          "listing_type",
          "additional_features",
          "electricity_available",
          "soil_type",
          "current_usage",
          "crops_grown",
          "farm_infrastructure",
          "connectivity",
          "approvals",
          "country",
          "state_name",
          "city",
          "locality",
          "sub_locality",
          "landmark",
          "address",
          "pincode",
          "agriculture_highlights",
        ],

        editableFields: ["land_area", "total_price", "price_per_unit", "rent_amount"],
      },
    },

    additional_features: {
      section: "agriculture_details",

      priority: 6,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "Which additional agricultural land features are available?",

      options: [
        "Corner Plot",
        "Boundary Wall",
        "Fencing",
        "Water Connection",
        "Electricity Available",
        "Bore Available",
        "Cement Road",
        "BT Road",
        "Gravel Road",
        "Mud Road",
        "Borewell",
        "Open Well",
        "Canal Water",
        "Drip Irrigation",
        "Sprinkler Irrigation",
        "River Access",
        "Pond Water",
        "Rainwater Harvesting",
      ],
    },

    electricity_available: {
      section: "agriculture_details",

      priority: 7,

      type: "single_select",

      required: false,

      question: "Is electricity connection available on the agricultural land?",

      options: ["Yes", "No"],
    },

    soil_type: {
      section: "agriculture_details",

      priority: 8,

      type: "single_select",

      required: false,

      question: "What is the soil type?",

      options: ["Red Soil", "Black Soil", "Clay Soil", "Sandy Soil", "Loamy Soil", "Mixed Soil"],
    },

    current_usage: {
      section: "agriculture_details",

      priority: 9,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "What is the current usage of this agricultural land?",

      options: [
        "Currently Cultivated",
        "Vacant Land",
        "Organic Farming",
        "Poultry",
        "Dairy",
        "Fish Farming",
        "Plantation",
      ],
    },

    crops_grown: {
      section: "agriculture_details",

      priority: 10,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "Which crops are currently grown here?",

      options: [
        "Paddy",
        "Cotton",
        "Maize",
        "Mango",
        "Coconut",
        "Banana",
        "Sugarcane",
        "Vegetables",
        "Flowers",
        "Oil Palm",
        "Tea",
        "Coffee",
      ],
    },

    farm_infrastructure: {
      section: "agriculture_details",

      priority: 11,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "What farm infrastructure is available on the property?",

      options: [
        "Farm House",
        "Storage Shed",
        "Tractor Access",
        "Fencing",
        "Boundary Wall",
        "Workers Quarters",
        "Cold Storage",
        "Greenhouse",
        "Polyhouse",
        "Cattle Shed",
      ],
    },

    connectivity: {
      section: "agriculture_details",

      priority: 12,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "What connectivity advantages does this agricultural land have?",

      options: [
        "Main Road Access",
        "Village Road Access",
        "Highway Access",
        "Near Market Yard",
        "Near Town",
        "Near River",
      ],
    },

    approvals: {
      section: "legal",

      priority: 14,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "What legal approvals or agriculture documents are available?",

      options: [
        "Clear Title",
        "Passbook Available",
        "Survey Number Available",
        "Pattadar Passbook",
        "EC Available",
        "Government Approved",
      ],
    },

    total_price: {
      section: "pricing",

      priority: 15,

      type: "price",

      required: false,

      visibleIf: {
        field: "listing_type",
        equals: "Buy",
      },

      question: "What is the total agricultural land price?",

      smartSuggestions: {
        enabled: true,

        examples: ["25 Lakhs", "50 Lakhs", "1 Crore", "5 Crore"],
      },
    },

    price_per_unit: {
      section: "pricing",

      priority: 16,

      type: "price_per_unit",

      required: false,

      visibleIf: {
        field: "listing_type",
        equals: "Buy",
      },

      question: "What is the price per unit?",

      dynamicUnitSource: {
        from: ["land_area"],
      },

      autoCalculation: {
        enabled: true,

        calculate: "price_per_unit",

        formula: "Number(total_price) / Number((land_area?.value))",
      },
    },

    rent_amount: {
      section: "pricing",

      priority: 17,

      type: "rental_price",

      required: false,

      visibleIf: {
        field: "listing_type",
        in: ["Rent", "Lease"],
      },

      question: "What is the monthly rental or lease amount?",
    },

    partnership_details: {
      section: "pricing",

      priority: 18,

      type: "textarea",

      required: false,

      visibleIf: {
        field: "listing_type",
        equals: "Partnership",
      },

      question: "What type of agricultural partnership are you looking for?",

      smartSuggestions: {
        enabled: true,

        examples: [
          "Profit sharing farming partnership",
          "Long-term agricultural lease partnership",
          "Organic farming collaboration",
          "Joint cultivation agreement",
        ],
      },
    },

    payment_options: {
      section: "legal",

      priority: 19,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "What payment options are available?",

      options: [
        "Price Negotiable",
        "Installments Available",
        "Investor Friendly",
        "Partnership Available",
        "Immediate Registration",
      ],
    },

    location: {
      section: "location",

      priority: 13,

      type: "smart_location",

      renderMode: "widget",

      widgetType: "smart_location",

      widget: "SmartLocationWidget",

      required: true,

      question: "Let's add the agricultural land location details.",

      groupedFields: [
        "country",
        "state_name",
        "city",
        "locality",
        "sub_locality",
        "landmark",
        "address",
        "pincode",
        "google_maps_link",
        "latitude",
        "longitude",
      ],
    },

    media_uploads: {
      section: "finalization",

      priority: 20,

      type: "media_upload",

      required: false,

      question: "Upload farm images, land documents or videos for AI auto-fill.",
    },

    agriculture_highlights: {
      section: "finalization",

      priority: 21,

      type: "multi_select",

      required: false,

      maxSelections: 3,

      question: "Select up to 3 agricultural land highlights.",

      options: [
        "Water Rich Land",
        "Fertile Soil",
        "Organic Farm",
        "High Yield Land",
        "Road Facing",
        "Near Highway",
        "Investment Hotspot",
        "Clear Title",
        "Ready Farm",
        "River View",
        "Fully Fenced",
        "Premium Farm",
      ],
    },

    property_description: {
      section: "finalization",

      priority: 999,

      type: "ai_generated_text",

      required: false,

      aiGenerated: true,

      hiddenFromConversation: true,

      autoGenerateFrom: [
        "agricultural_land_type",
        "land_area",
        "soil_type",
        "crops_grown",
        "farm_infrastructure",
        "connectivity",
        "approvals",
        "additional_features",
        "location",
        "price_per_unit",
      ],
    },

    assign_nearest_agent: {
      section: "finalization",

      priority: 22,

      type: "single_select",

      required: false,

      question: "Do you want to assign this property to the nearest agent? Agent commission may apply.",

      options: ["Yes", "No"],
    },
  },

  autoGeneration: {
    enabled: true,

    generateTitle: true,

    generateDescription: true,

    generateSEODescription: true,

    generateHighlights: true,

    generateTags: true,

    generatePropertySummary: true,

    triggerAfterFlowCompletion: true,
  },

  uploadSupport: {
    enabled: true,

    allowImages: true,

    allowPDFs: true,

    allowBrochures: true,

    autoExtractPropertyData: true,

    autoDetectPricing: true,

    autoDetectLocation: true,

    autoDetectAmenities: true,

    askOnlyMissingFieldsAfterExtraction: true,
  },

  submitFlow: {
    enabled: true,

    showPreviewBeforeSubmit: true,

    autoGenerateFinalSummary: true,

    showAIQualityScore: true,

    verifyRequiredFields: true,
  },

  rules: [
    {
      type: "dynamic_next_question",
    },
    {
      type: "skip_hidden_questions",
    },
    {
      type: "clear_hidden_values",
    },
    {
      type: "prevent_duplicate_questions",
    },
    {
      type: "dynamic_followup_questions",
    },
    {
      type: "recalculate_visibility_after_each_answer",
    },
    {
      type: "ask_only_relevant_questions",
    },
    {
      type: "smart_skip_logic",
    },
    {
      type: "price_auto_calculation",
    },
    {
      type: "multi_variant_property_clone",
    },
    {
      type: "auto_generate_description",
    },
    {
      type: "agriculture_dependency_flow",
    },
  ],
};

export default agriculturalFlow;
