import type { PropertyFlowConfig } from "@/engines/types";

const COMMERCIAL_TYPES = [
  "Office Space",
  "Coworking Space",
  "Shop / Retail Store",
  "Showroom",
  "Commercial Building",
  "Warehouse / Godown",
  "Industrial Shed",
  "Factory",
  "Restaurant / Cafe Space",
  "Hotel / Lodge Building",
  "Clinic / Hospital Space",
  "Educational Institute",
  "Commercial Land / Plot",
  "Business Center",
];

const BUILT_AREA_TYPES = [
  "Office Space",
  "Coworking Space",
  "Shop / Retail Store",
  "Showroom",
  "Commercial Building",
  "Warehouse / Godown",
  "Industrial Shed",
  "Factory",
  "Restaurant / Cafe Space",
  "Hotel / Lodge Building",
  "Clinic / Hospital Space",
  "Educational Institute",
  "Business Center",
];

const NON_LAND_TYPES = BUILT_AREA_TYPES;

const BUSINESS_SPACE_TYPES = [
  "Office Space",
  "Coworking Space",
  "Business Center",
  "Clinic / Hospital Space",
  "Educational Institute",
];

export const commercialFlow: PropertyFlowConfig = {
  id: "commercial",

  category: "commercial",

  label: "Commercial",

  version: "v2-client-commercial-fully-aligned",

  engine: {
    mode: "dynamic_conversation",

    strictVisibilityResolution: true,

    dynamicQuestionResolver: true,

    reevaluateOnEveryAnswer: true,

    skipHiddenQuestions: true,

    clearHiddenFieldValues: true,

    preventDuplicateQuestions: true,

    removeIrrelevantQuestions: true,

    conversationMemory: true,

    smartConditionalFlow: true,

    supportContextualQuestions: true,

    supportAIExtraction: true,

    supportNaturalCorrections: true,

    supportConversationalAI: true,

    autoRevalidateDependencies: true,

    dynamicSectionActivation: true,

    clonePropertySupport: true,

    multiVariantSupport: true,

    preserveParentDataDuringClone: true,

    AIBasedNextQuestionSelection: true,

    progressiveConversationMode: true,

    intelligentDependencyRouting: true,

    contextualSkipLogic: true,

    askOnlyContextualQuestions: true,

    propertyTypeAwareQuestions: true,

    dynamicFlowReordering: true,
  },

  ai: {
    enabled: true,

    askOneQuestionAtATime: true,

    askOnlyRelevantQuestions: true,

    askOnlyMissingFields: true,

    supportGreetings: true,

    supportNaturalLanguage: true,

    supportCorrections: true,

    supportSkipIntent: true,

    supportIntentDetection: true,

    supportContextAwareness: true,

    supportConversationalMemory: true,

    supportDocumentExtraction: true,

    supportImageExtraction: true,

    supportAutoFill: true,

    supportDynamicFollowups: true,

    supportPriceCalculation: true,

    supportSmartSuggestions: true,

    supportHumanReplies: true,

    autoGenerateDescription: true,

    autoGenerateTitle: true,

    autoGenerateSEO: true,

    supportVariantDetection: true,

    supportContextualCommercialQuestions: true,

    supportOptionalSectionSkipping: true,
  },

  sections: [
    {
      id: "basic_information",
      label: "Basic Information",
      priority: 1,
    },

    {
      id: "property_configuration",
      label: "Commercial Configuration",
      priority: 2,
    },

    {
      id: "pricing",
      label: "Pricing",
      priority: 3,
    },

    {
      id: "business_details",
      label: "Business Details",
      priority: 4,
    },

    {
      id: "features",
      label: "Features & Amenities",
      priority: 5,
    },

    {
      id: "location",
      label: "Location",
      priority: 6,
    },

    {
      id: "legal",
      label: "Legal & Approvals",
      priority: 7,
    },

    {
      id: "finalization",
      label: "Finalization",
      priority: 8,
    },
  ],

  fields: {
    property_type: {
      section: "basic_information",

      priority: 1,

      type: "single_select",

      required: true,

      question: "What type of commercial property are you listing?",

      options: COMMERCIAL_TYPES,
    },

    listed_by: {
      section: "basic_information",

      priority: 2,

      type: "single_select",

      required: true,

      question: "Who is listing this commercial property?",

      options: ["Owner", "Agent", "Builder"],
    },

    listing_type: {
      section: "basic_information",

      priority: 3,

      type: "single_select",

      required: true,

      question: "Is this property for Buy, Rent or Lease?",

      options: ["Buy", "Rent", "Lease"],

      invalidateOnChange: [
        "available_from_date",
        "possession_date",
        "property_age",
        "rent_amount",
        "total_price",
        "price_per_unit",
      ],
    },

    property_condition: {
      section: "basic_information",

      priority: 4,

      type: "single_select",

      required: true,

      question: "What is the property condition?",

      options: ["New", "Resale", "Ready to Occupy", "Under Construction"],
    },

    available_from_date: {
      section: "basic_information",

      priority: 5,

      type: "future_date",

      renderAs: "calendar",

      required: false,

      visibleIf: {
        field: "property_condition",
        equals: "Ready to Occupy",
      },

      question: "When is the property available from?",
    },

    possession_date: {
      section: "basic_information",

      priority: 6,

      type: "future_date",

      renderAs: "calendar",

      required: false,

      visibleIf: {
        field: "property_condition",
        equals: "Under Construction",
      },

      question: "When is the possession expected?",
    },

    property_age: {
      section: "basic_information",

      priority: 7,

      type: "single_select",

      required: false,

      visibleIf: {
        field: "property_condition",
        equals: "Resale",
      },

      question: "What is the property age?",

      options: ["0-1 Years", "1-5 Years", "5-10 Years", "10+ Years"],
    },

    built_area: {
      section: "property_configuration",

      priority: 8,

      type: "measurement",

      required: true,

      requiredIfVisible: true,

      visibleIf: {
        field: "property_type",
        in: BUILT_AREA_TYPES,
      },

      question: "What is the built area size?",

      units: ["Sq Ft"],

      aiFollowup: {
        triggerAfterAnswer: true,
        askForVariants: true,
        followupQuestion: "Do you have additional commercial area sizes available for separate listings?",
      },
    },

    land_size: {
      section: "property_configuration",

      priority: 9,

      type: "measurement",

      required: true,

      requiredIfVisible: true,

      visibleIf: {
        field: "property_type",
        equals: "Commercial Land / Plot",
      },

      question: "What is the land size?",

      units: ["Sq Ft", "Sq Yard", "Cent", "Gunta", "Acre", "Bigha"],
    },

    add_multiple_sizes: {
      section: "property_configuration",

      priority: 10,

      type: "single_select",

      required: false,

      visibleIf: {
        field: "property_type",
        in: BUILT_AREA_TYPES,
      },

      question: "Do you want to add multiple area variants?",

      options: ["Yes", "No"],
    },

    commercial_variants: {
      section: "property_configuration",

      priority: 11,

      type: "multi_variant_group",

      required: false,

      visibleIf: {
        field: "add_multiple_sizes",
        equals: "Yes",
      },

      question: "Add all available commercial area variants.",

      cloneStrategy: {
        enabled: true,

        preserveFields: [
          "property_type",
          "listed_by",
          "listing_type",
          "country",
          "state_name",
          "city",
          "locality",
          "sub_locality",
          "landmark",
          "address",
          "pincode",
          "commercial_amenities",
          "approvals",
          "property_highlights",
        ],

        editableFields: ["built_area", "land_size", "total_price", "rent_amount", "floor_number"],
      },
    },

    floor_number: {
      section: "property_configuration",

      priority: 12,

      type: "number",

      required: false,

      visibleIf: {
        field: "property_type",
        in: NON_LAND_TYPES,
      },

      question: "Which floor is this commercial property on?",
    },

    total_floors: {
      section: "property_configuration",

      priority: 13,

      type: "number",

      required: false,

      visibleIf: {
        field: "property_type",
        in: NON_LAND_TYPES,
      },

      question: "How many total floors are there in the building?",
    },

    total_price: {
      section: "pricing",

      priority: 14,

      type: "price",

      required: false,

      visibleIf: {
        field: "listing_type",
        equals: "Buy",
      },

      question: "What is the total property price?",

      smartSuggestions: {
        enabled: true,

        examples: ["25 Lakhs", "50 Lakhs", "1 Crore", "2.50 Crore"],
      },
    },

    price_per_unit: {
      section: "pricing",

      priority: 15,

      type: "price_per_unit",

      required: false,

      visibleIf: {
        field: "listing_type",
        equals: "Buy",
      },

      question: "What is the price per unit?",

      dynamicUnitSource: {
        from: ["built_area", "land_size"],
      },

      autoCalculation: {
        enabled: true,

        calculate: "price_per_unit",

        formula: "total_price / (built_area || land_size)",
      },
    },

    rent_amount: {
      section: "pricing",

      priority: 16,

      type: "rental_price",

      required: false,

      visibleIf: {
        field: "listing_type",
        in: ["Rent", "Lease"],
      },

      question: "What is the monthly rent amount?",

      smartSuggestions: {
        enabled: true,

        examples: ["5000 Per Month", "25000 Per Month"],
      },
    },

    business_space_details: {
      section: "business_details",

      priority: 23,

      type: "multi_select",

      required: false,

      visibleIf: {
        field: "property_type",
        in: BUSINESS_SPACE_TYPES,
      },

      allowSkipGroup: true,

      question: "What business space facilities are available?",

      options: ["Cabins", "Meeting Rooms", "Conference Rooms", "Washrooms", "Reception Area", "Pantry"],
    },

    parking: {
      section: "business_details",

      priority: 24,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "What parking options are available?",

      options: ["Car Parking", "Bike Parking", "Visitor Parking"],
    },

    furnishing_status: {
      section: "features",

      priority: 17,

      type: "single_select",

      required: false,

      visibleIf: {
        field: "property_type",
        in: NON_LAND_TYPES,
      },

      question: "What is the furnishing status?",

      options: ["Unfurnished", "Semi Furnished", "Fully Furnished"],
    },

    currently_operating_as: {
      section: "business_details",

      priority: 19,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "What is this property currently operating as?",

      options: [
        "Office",
        "Retail Store",
        "Restaurant",
        "Cafe",
        "Salon",
        "Clinic",
        "Gym",
        "Warehouse",
        "Coworking Space",
        "Training Institute",
        "Supermarket",
        "Hotel",
        "Manufacturing Unit",
        "Vacant",
      ],
    },

    commercial_furnishing: {
      section: "features",

      priority: 18,

      type: "multi_select",

      required: false,

      visibleIf: {
        field: "furnishing_status",
        in: ["Semi Furnished", "Fully Furnished"],
      },

      allowSkipGroup: true,

      question: "Which commercial furnishing items are available?",

      options: [
        "Workstations",
        "Cabins",
        "Reception",
        "Conference Room",
        "Central AC",
        "Power Backup",
        "Internet",
        "CCTV",
        "Server Room",
        "Pantry",
        "False Ceiling",
        "Fire Safety",
      ],
    },

    suitable_for: {
      section: "features",

      priority: 20,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "Which businesses is this property suitable for?",

      options: [
        "IT Company",
        "Retail Store",
        "Restaurant",
        "Cafe",
        "Clinic",
        "Hospital",
        "Salon",
        "Gym",
        "Warehouse",
        "Startup",
        "Bank",
        "Showroom",
        "Training Center",
        "Coaching Center",
        "Call Center",
      ],
    },

    commercial_amenities: {
      section: "features",

      priority: 21,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "Which commercial amenities are available?",

      options: [
        "Lift",
        "Power Backup",
        "24/7 Security",
        "Visitor Parking",
        "Fire Safety",
        "CCTV",
        "Central AC",
        "Loading Area",
        "Freight Elevator",
        "Reception",
        "High Speed Internet",
        "Access Control",
      ],
    },

    visibility_access: {
      section: "features",

      priority: 22,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "What visibility and access advantages does the property have?",

      options: [
        "Main Road Facing",
        "Corner Property",
        "High Footfall Area",
        "Near Metro",
        "Highway Access",
        "Truck Access",
      ],
    },

    payment_options: {
      section: "legal",

      priority: 25,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "What payment options are available?",

      options: [
        "Price Negotiable",
        "Bank Loan Available",
        "EMI Available",
        "Installments Available",
        "Flexible Payment Plan",
        "Construction Linked Payment",
        "Possession Linked Payment",
        "Zero Down Payment",
        "Low Booking Amount",
        "Assured Rental Returns",
        "Investor Friendly",
        "NRI Assistance",
        "Pre-EMI Support",
        "Premium Bank Tie-Ups",
        "Custom Payment Plans",
        "Immediate Registration",
      ],
    },

    approvals: {
      section: "legal",

      priority: 26,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "What approvals does this property have?",

      options: [
        "RERA Approved",
        "Fire NOC",
        "Trade License",
        "Occupancy Certificate",
        "Municipal Approved",
        "Pollution Clearance",
        "Approved Layout",
      ],
    },

    location: {
      section: "location",

      priority: 27,

      type: "smart_location",

      renderMode: "widget",

      widgetType: "smart_location",

      widget: "SmartLocationWidget",

      required: true,

      question: "Let's add the commercial property location details.",

      groupedFields: [
        "country",
        "state_name",
        "city",
        "locality",
        "sub_locality",
        "landmark",
        "address",
        "pincode",
        "google_maps_link",
        "latitude",
        "longitude",
      ],
    },

    property_highlights: {
      section: "finalization",

      priority: 28,

      type: "multi_select",

      required: false,

      maxSelections: 3,

      question: "Select up to 3 commercial property highlights.",

      options: [
        "Prime Location",
        "IT Corridor",
        "High Footfall",
        "Near Metro",
        "Ready Business Space",
        "Investment Opportunity",
        "Premium Commercial",
        "Fully Operational",
        "Corner Property",
        "High ROI",
        "Main Road Facing",
        "Startup Friendly",
        "Business Hub",
      ],
    },

    property_description: {
      section: "finalization",

      priority: 999,

      type: "ai_generated_text",

      required: false,

      aiGenerated: true,

      hiddenFromConversation: true,

      autoGenerateFrom: [
        "property_type",
        "location",
        "furnishing_status",
        "commercial_amenities",
        "visibility_access",
        "pricing",
        "suitable_for",
        "currently_operating_as",
      ],
    },

    assign_nearest_agent: {
      section: "finalization",

      priority: 30,

      type: "single_select",

      required: false,

      question: "Do you want to assign this property to the nearest agent? Agent commission may apply.",

      options: ["Yes", "No"],
    },
  },

  autoGeneration: {
    enabled: true,

    generateTitle: true,

    generateDescription: true,

    generateSEODescription: true,

    generateHighlights: true,

    generateTags: true,

    generatePropertySummary: true,

    triggerAfterFlowCompletion: true,
  },

  uploadSupport: {
    enabled: true,

    allowImages: true,

    allowPDFs: true,

    allowBrochures: true,

    autoExtractPropertyData: true,

    autoDetectPricing: true,

    autoDetectLocation: true,

    autoDetectAmenities: true,

    askOnlyMissingFieldsAfterExtraction: true,
  },

  submitFlow: {
    enabled: true,

    showPreviewBeforeSubmit: true,

    autoGenerateFinalSummary: true,

    showAIQualityScore: true,

    verifyRequiredFields: true,
  },

  rules: [
    {
      type: "dynamic_next_question",
    },
    {
      type: "skip_hidden_questions",
    },
    {
      type: "clear_hidden_values",
    },
    {
      type: "prevent_duplicate_questions",
    },
    {
      type: "dynamic_followup_questions",
    },
    {
      type: "recalculate_visibility_after_each_answer",
    },
    {
      type: "ask_only_relevant_questions",
    },
    {
      type: "smart_skip_logic",
    },
    {
      type: "price_auto_calculation",
    },
    {
      type: "multi_variant_property_clone",
    },
    {
      type: "auto_generate_description",
    },
    {
      type: "contextual_commercial_flow",
    },
    {
      type: "commercial_property_dependency_flow",
    },
  ],
};

export default commercialFlow;
