import type { PropertyFlowConfig } from "@/engines/types";

const SHARED_SPACE_TYPES = [
  "Coworking Space",
  "Managed Office",
  "Private Cabin",
  "Dedicated Desk",
  "Hot Desk",
  "Meeting Room",
  "Conference Room",
  "Virtual Office",
  "Training Room",
  "Startup Space",
  "Shared Studio",
  "Creative Workspace",
  "Business Lounge",
  "Day Pass Workspace",
];

export const coworkingFlow: PropertyFlowConfig = {
  id: "coworking_shared_space",

  category: "coworking",

  label: "Co-working & Shared Spaces",

  version: "v1-client-aligned-coworking",

  engine: {
    mode: "dynamic_conversation",

    strictVisibilityResolution: true,

    dynamicQuestionResolver: true,

    reevaluateOnEveryAnswer: true,

    skipHiddenQuestions: true,

    clearHiddenFieldValues: true,

    preventDuplicateQuestions: true,

    removeIrrelevantQuestions: true,

    conversationMemory: true,

    smartConditionalFlow: true,

    supportContextualQuestions: true,

    supportAIExtraction: true,

    supportNaturalCorrections: true,

    supportConversationalAI: true,

    autoRevalidateDependencies: true,

    dynamicSectionActivation: true,

    clonePropertySupport: true,

    multiVariantSupport: true,

    preserveParentDataDuringClone: true,

    AIBasedNextQuestionSelection: true,

    progressiveConversationMode: true,

    intelligentDependencyRouting: true,

    contextualSkipLogic: true,

    askOnlyContextualQuestions: true,

    propertyTypeAwareQuestions: true,

    dynamicFlowReordering: true,
  },

  ai: {
    enabled: true,

    askOneQuestionAtATime: true,

    askOnlyRelevantQuestions: true,

    askOnlyMissingFields: true,

    supportGreetings: true,

    supportNaturalLanguage: true,

    supportCorrections: true,

    supportSkipIntent: true,

    supportIntentDetection: true,

    supportContextAwareness: true,

    supportConversationalMemory: true,

    supportDocumentExtraction: true,

    supportImageExtraction: true,

    supportAutoFill: true,

    supportDynamicFollowups: true,

    supportPriceCalculation: true,

    supportSmartSuggestions: true,

    supportHumanReplies: true,

    autoGenerateDescription: true,

    autoGenerateTitle: true,

    autoGenerateSEO: true,

    supportVariantDetection: true,

    supportOptionalSectionSkipping: true,
  },

  sections: [
    {
      id: "basic_information",

      label: "Basic Information",

      priority: 1,
    },

    {
      id: "workspace_configuration",

      label: "Workspace Configuration",

      priority: 2,
    },

    {
      id: "pricing",

      label: "Pricing",

      priority: 3,
    },

    {
      id: "workspace_features",

      label: "Workspace Features",

      priority: 4,
    },

    {
      id: "availability",

      label: "Availability",

      priority: 5,
    },

    {
      id: "location",

      label: "Location",

      priority: 6,
    },

    {
      id: "finalization",

      label: "Finalization",

      priority: 7,
    },
  ],

  fields: {
    shared_space_type: {
      section: "basic_information",

      priority: 1,

      type: "single_select",

      required: true,

      question: "What type of shared workspace is this?",

      options: SHARED_SPACE_TYPES,
    },

    listed_by: {
      section: "basic_information",

      priority: 2,

      type: "single_select",

      required: true,

      question: "Who is listing this workspace?",

      options: ["Owner", "Operator", "Coworking Brand", "Agent"],
    },

    listing_type: {
      section: "basic_information",

      priority: 3,

      type: "single_select",

      required: true,

      question: "What type of workspace plan is available?",

      options: ["Hourly", "Daily", "Weekly", "Monthly", "Yearly Lease"],

      invalidateOnChange: [
        "hourly_price",
        "daily_pass_price",
        "weekly_price",
        "monthly_rent",
        "price_per_seat",
        "security_deposit",
        "maintenance_charges",
      ],
    },

    total_seats: {
      section: "workspace_configuration",

      priority: 4,

      type: "number",

      required: true,

      question: "How many total seats are available?",
    },

    available_seats: {
      section: "workspace_configuration",

      priority: 5,

      type: "number",

      required: true,

      question: "How many seats are currently available?",
    },

    private_cabins: {
      section: "workspace_configuration",

      priority: 6,

      type: "number",

      required: false,

      question: "How many private cabins are available?",
    },

    meeting_rooms: {
      section: "workspace_configuration",

      priority: 7,

      type: "number",

      required: false,

      question: "How many meeting rooms are available?",
    },

    conference_rooms: {
      section: "workspace_configuration",

      priority: 8,

      type: "number",

      required: false,

      question: "How many conference rooms are available?",
    },

    floor_number: {
      section: "workspace_configuration",

      priority: 9,

      type: "number",

      required: false,

      question: "Which floor is this workspace located on?",
    },

    total_floors: {
      section: "workspace_configuration",

      priority: 10,

      type: "number",

      required: false,

      question: "How many total floors are there in the building?",
    },

    built_area: {
      section: "workspace_configuration",

      priority: 11,

      type: "measurement",

      required: true,

      question: "What is the built area size?",

      units: ["Sq Ft"],
    },

    hourly_price: {
      section: "pricing",

      priority: 12,

      type: "price",

      required: false,

      visibleIf: {
        field: "listing_type",
        equals: "Hourly",
      },

      question: "What is the hourly workspace price?",
    },

    daily_pass_price: {
      section: "pricing",

      priority: 13,

      type: "price",

      required: false,

      visibleIf: {
        field: "listing_type",
        equals: "Daily",
      },

      question: "What is the daily pass price?",
    },

    weekly_price: {
      section: "pricing",

      priority: 14,

      type: "price",

      required: false,

      visibleIf: {
        field: "listing_type",
        equals: "Weekly",
      },

      question: "What is the weekly workspace price?",
    },

    monthly_rent: {
      section: "pricing",

      priority: 15,

      type: "rental_price",

      required: false,

      visibleIf: {
        field: "listing_type",
        in: ["Monthly", "Yearly Lease"],
      },

      question: "What is the monthly workspace rent?",
    },

    price_per_seat: {
      section: "pricing",

      priority: 16,

      type: "price",

      required: false,

      visibleIf: {
        field: "listing_type",
        in: ["Monthly", "Yearly Lease"],
      },

      question: "What is the price per seat?",
    },

    security_deposit: {
      section: "pricing",

      priority: 17,

      type: "price",

      required: false,

      visibleIf: {
        field: "listing_type",
        equals: "Yearly Lease",
      },

      question: "What is the security deposit amount?",
    },

    maintenance_charges: {
      section: "pricing",

      priority: 18,

      type: "price",

      required: false,

      visibleIf: {
        field: "listing_type",
        equals: "Yearly Lease",
      },

      question: "What are the monthly maintenance charges?",
    },

    workspace_features: {
      section: "workspace_features",

      priority: 19,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "Which workspace features are available?",

      options: [
        "High Speed Internet",
        "WiFi",
        "Power Backup",
        "Central AC",
        "Reception",
        "Cafeteria",
        "Pantry",
        "Printer",
        "Scanner",
        "Projector",
        "Whiteboard",
        "Locker",
        "Phone Booth",
        "Mail Handling",
        "Business Address",
      ],
    },

    office_amenities: {
      section: "workspace_features",

      priority: 20,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "Which office amenities are available?",

      options: [
        "Parking",
        "Visitor Parking",
        "Lift",
        "24/7 Access",
        "Security",
        "CCTV",
        "Biometric Access",
        "Housekeeping",
        "Fire Safety",
        "Wheelchair Access",
        "Smoking Zone",
        "Lounge Area",
      ],
    },

    currently_operating_as: {
      section: "workspace_features",

      priority: 21,

      type: "single_select",

      required: false,

      question: "What is this workspace currently operating as?",

      options: [
        "Startup Hub",
        "IT Workspace",
        "Training Center",
        "Shared Office",
        "Creative Studio",
        "Business Center",
        "Vacant",
      ],
    },

    industries_working_here: {
      section: "workspace_features",

      priority: 22,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "Which industries or technologies currently work here?",

      options: [
        "AI / Machine Learning",
        "Software Development",
        "SAP",
        "Cloud Computing",
        "Cyber Security",
        "Data Science",
        "Blockchain",
        "Web Development",
        "Mobile App Development",
        "Digital Marketing",
        "UI/UX Design",
        "Content Creation",
        "Finance / FinTech",
        "EdTech",
        "HealthTech",
        "E-Commerce",
        "Gaming",
        "Media Production",
        "Consulting",
        "Legal Services",
        "Recruitment",
        "Architecture",
        "Real Estate",
      ],
    },

    community_type: {
      section: "workspace_features",

      priority: 23,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "What type of community does this workspace support?",

      options: [
        "Startup Community",
        "Tech Community",
        "Creative Community",
        "Freelancer Hub",
        "Corporate Teams",
        "Women Entrepreneurs",
        "Student Startups",
        "Remote Workers",
        "Founders Network",
        "Investor Network",
      ],
    },

    suitable_for: {
      section: "workspace_features",

      priority: 24,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "Who is this workspace suitable for?",

      options: [
        "Freelancers",
        "Startups",
        "IT Companies",
        "Remote Teams",
        "Design Studios",
        "Training Institutes",
        "Consultants",
        "Agencies",
        "Content Creators",
        "Small Businesses",
      ],
    },

    available_from: {
      section: "availability",

      priority: 25,

      type: "future_date",

      renderAs: "calendar",

      required: false,

      question: "When will this workspace be available from?",
    },

    access_24x7: {
      section: "availability",

      priority: 26,

      type: "single_select",

      required: false,

      question: "Is 24/7 workspace access available?",

      options: ["Yes", "No"],
    },

    working_hours: {
      section: "availability",

      priority: 27,

      type: "text",

      required: false,

      question: "What are the workspace operating hours?",
    },

    payment_options: {
      section: "pricing",

      priority: 28,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "What payment options are available?",

      options: [
        "Flexible Plans",
        "No Lock-In",
        "Zero Deposit",
        "Monthly Billing",
        "Corporate Billing",
        "Custom Plans",
        "Startup Discounts",
      ],
    },

    location: {
      section: "location",

      priority: 29,

      type: "smart_location",

      renderMode: "widget",

      widgetType: "smart_location",

      widget: "SmartLocationWidget",

      required: true,

      question: "Let's add the coworking space location details.",

      groupedFields: [
        "country",
        "state_name",
        "city",
        "locality",
        "sub_locality",
        "landmark",
        "address",
        "pincode",
        "google_maps_link",
        "latitude",
        "longitude",
      ],
    },

    coworking_highlights: {
      section: "finalization",

      priority: 30,

      type: "multi_select",

      required: false,

      maxSelections: 3,

      question: "Select up to 3 workspace highlights.",

      options: [
        "Startup Friendly",
        "Near Metro",
        "Fully Managed",
        "Premium Workspace",
        "24/7 Access",
        "High Speed Internet",
        "Flexible Plans",
        "Business Hub",
        "Creative Workspace",
        "Top Rated",
        "Community Driven",
      ],
    },

    property_description: {
      section: "finalization",

      priority: 999,

      type: "ai_generated_text",

      required: false,

      aiGenerated: true,

      hiddenFromConversation: true,

      autoGenerateFrom: [
        "shared_space_type",
        "total_seats",
        "available_seats",
        "workspace_features",
        "office_amenities",
        "industries_working_here",
        "community_type",
        "location",
        "price_per_seat",
      ],
    },

    assign_nearest_agent: {
      section: "finalization",

      priority: 32,

      type: "single_select",

      required: false,

      question: "Do you want to assign this property to the nearest agent? Agent commission may apply.",

      options: ["Yes", "No"],
    },
  },

  autoGeneration: {
    enabled: true,

    generateTitle: true,

    generateDescription: true,

    generateSEODescription: true,

    generateHighlights: true,

    generateTags: true,

    generatePropertySummary: true,

    triggerAfterFlowCompletion: true,
  },

  uploadSupport: {
    enabled: true,

    allowImages: true,

    allowPDFs: true,

    allowBrochures: true,

    autoExtractPropertyData: true,

    autoDetectPricing: true,

    autoDetectLocation: true,

    autoDetectAmenities: true,

    askOnlyMissingFieldsAfterExtraction: true,
  },

  submitFlow: {
    enabled: true,

    showPreviewBeforeSubmit: true,

    autoGenerateFinalSummary: true,

    showAIQualityScore: true,

    verifyRequiredFields: true,
  },

  rules: [
    {
      type: "dynamic_next_question",
    },
    {
      type: "skip_hidden_questions",
    },
    {
      type: "clear_hidden_values",
    },
    {
      type: "prevent_duplicate_questions",
    },
    {
      type: "dynamic_followup_questions",
    },
    {
      type: "recalculate_visibility_after_each_answer",
    },
    {
      type: "ask_only_relevant_questions",
    },
    {
      type: "smart_skip_logic",
    },
    {
      type: "price_auto_calculation",
    },
    {
      type: "multi_variant_property_clone",
    },
    {
      type: "auto_generate_description",
    },
    {
      type: "coworking_dependency_flow",
    },
  ],
};

export default coworkingFlow;
