import type { PropertyFlowConfig } from "@/engines/types";

const FINANCIAL_PROVIDER_TYPES = [
  "Bank",
  "NBFC",
  "Housing Finance Company (HFC)",
  "DSA / Loan Agent",
  "Insurance Company",
  "Investment Advisory",
  "Legal Consultant",
  "Property Valuer",
];

const FINANCIAL_SERVICES = [
  "Home Loan",
  "Loan Against Property / Mortgage",
  "Property Legal Services",
  "Property Valuation",
  "Investment Advisory",
  "Credit Score Improvement",
  "Commercial Loan",
  "Insurance",
];

export const financialFlow = {
  id: "financial",

  category: "financial",

  label: "Financial Services",

  version: "v1-financial-provider-flow",

  engine: {
    mode: "dynamic_conversation",

    strictVisibilityResolution: true,

    dynamicQuestionResolver: true,

    reevaluateOnEveryAnswer: true,

    skipHiddenQuestions: true,

    clearHiddenFieldValues: true,

    preventDuplicateQuestions: true,

    removeIrrelevantQuestions: true,

    conversationMemory: true,

    smartConditionalFlow: true,

    supportContextualQuestions: true,

    supportAIExtraction: true,

    supportNaturalCorrections: true,

    supportConversationalAI: true,

    autoRevalidateDependencies: true,

    dynamicSectionActivation: true,

    clonePropertySupport: false,

    multiVariantSupport: false,
  },

  ai: {
    enabled: true,

    askOneQuestionAtATime: true,

    askOnlyRelevantQuestions: true,

    askOnlyMissingFields: true,

    supportGreetings: true,

    supportNaturalLanguage: true,

    supportCorrections: true,

    supportSkipIntent: true,

    supportIntentDetection: true,

    supportContextAwareness: true,

    supportConversationalMemory: true,

    supportAutoFill: true,

    supportDynamicFollowups: true,

    supportSmartSuggestions: true,

    supportHumanReplies: true,

    autoGenerateDescription: true,

    autoGenerateTitle: true,
  },

  sections: [
    {
      id: "basic_information",
      label: "Basic Information",
      priority: 1,
    },

    {
      id: "service_configuration",
      label: "Services Offered",
      priority: 2,
    },

    {
      id: "pricing",
      label: "Pricing & Charges",
      priority: 3,
    },

    {
      id: "coverage",
      label: "Coverage & Contact",
      priority: 4,
    },

    {
      id: "kyc",
      label: "KYC & Documents",
      priority: 5,
    },
  ],

  fields: {
    provider_type: {
      section: "basic_information",
      priority: 1,
      type: "single_select",
      required: true,
      question: "What type of financial service provider are you?",
      options: FINANCIAL_PROVIDER_TYPES,
    },

    company_name: {
      section: "basic_information",
      priority: 2,
      type: "text",
      required: true,
      question: "What is the company / provider name?",
      placeholder: "e.g. ABC Housing Finance Ltd.",
    },

    listed_by: {
      section: "basic_information",
      priority: 3,
      type: "single_select",
      required: true,
      question: "Who is listing this service?",
      options: ["Owner", "Authorised Representative", "DSA Partner"],
    },

    services_offered: {
      section: "service_configuration",
      priority: 4,
      type: "multi_select",
      required: true,
      question: "Which financial services do you offer?",
      options: FINANCIAL_SERVICES,
    },

    min_loan_amount: {
      section: "pricing",
      priority: 5,
      type: "number",
      required: false,
      question: "Minimum loan / service amount (INR)?",
      placeholder: "e.g. 100000",
      visibleIf: {
        field: "services_offered",
        in: ["Home Loan", "Loan Against Property / Mortgage", "Commercial Loan"],
      },
    },

    max_loan_amount: {
      section: "pricing",
      priority: 6,
      type: "number",
      required: false,
      question: "Maximum loan / service amount (INR)?",
      placeholder: "e.g. 10000000",
      visibleIf: {
        field: "services_offered",
        in: ["Home Loan", "Loan Against Property / Mortgage", "Commercial Loan"],
      },
    },

    interest_rate_min: {
      section: "pricing",
      priority: 7,
      type: "number",
      required: false,
      question: "Minimum interest rate (% per annum)?",
      placeholder: "e.g. 8.5",
      visibleIf: {
        field: "services_offered",
        in: ["Home Loan", "Loan Against Property / Mortgage", "Commercial Loan"],
      },
    },

    interest_rate_max: {
      section: "pricing",
      priority: 8,
      type: "number",
      required: false,
      question: "Maximum interest rate (% per annum)?",
      placeholder: "e.g. 14.5",
      visibleIf: {
        field: "services_offered",
        in: ["Home Loan", "Loan Against Property / Mortgage", "Commercial Loan"],
      },
    },

    processing_fee_percent: {
      section: "pricing",
      priority: 9,
      type: "number",
      required: false,
      question: "Processing fee (% of loan amount)?",
      placeholder: "e.g. 1.0",
      visibleIf: {
        field: "services_offered",
        in: ["Home Loan", "Loan Against Property / Mortgage", "Commercial Loan"],
      },
    },

    min_tenure_years: {
      section: "pricing",
      priority: 10,
      type: "number",
      required: false,
      question: "Minimum tenure (years)?",
      visibleIf: {
        field: "services_offered",
        in: ["Home Loan", "Loan Against Property / Mortgage", "Commercial Loan"],
      },
    },

    max_tenure_years: {
      section: "pricing",
      priority: 11,
      type: "number",
      required: false,
      question: "Maximum tenure (years)?",
      visibleIf: {
        field: "services_offered",
        in: ["Home Loan", "Loan Against Property / Mortgage", "Commercial Loan"],
      },
    },

    eligibility_criteria: {
      section: "service_configuration",
      priority: 12,
      type: "textarea",
      required: false,
      question: "Briefly describe your eligibility criteria.",
      placeholder: "e.g. Salaried / self-employed, CIBIL > 650, min. 2 years income...",
    },

    head_office_city: {
      section: "coverage",
      priority: 13,
      type: "city",
      required: true,
      question: "Which city is your head office located in?",
    },

    head_office_locality: {
      section: "coverage",
      priority: 14,
      type: "locality",
      required: false,
      question: "Head office locality / area?",
      dependsOn: ["head_office_city"],
    },

    service_states: {
      section: "coverage",
      priority: 15,
      type: "multi_select",
      required: false,
      question: "Which states do you service?",
      smartSuggestions: {
        enabled: true,
        searchable: true,
        chips: true,
      },
    },

    service_cities: {
      section: "coverage",
      priority: 16,
      type: "multi_select",
      required: false,
      question: "Which cities do you actively operate in?",
      smartSuggestions: {
        enabled: true,
        searchable: true,
        chips: true,
      },
    },

    website: {
      section: "coverage",
      priority: 17,
      type: "url",
      required: false,
      question: "Company website URL?",
      placeholder: "https://www.example.com",
    },

    contact_phone: {
      section: "coverage",
      priority: 18,
      type: "phone",
      required: true,
      question: "Primary contact phone number?",
    },

    contact_email: {
      section: "coverage",
      priority: 19,
      type: "email",
      required: false,
      question: "Primary contact email?",
    },

    pan_number: {
      section: "kyc",
      priority: 20,
      type: "text",
      required: false,
      question: "Company / Provider PAN number?",
      placeholder: "ABCDE1234F",
    },

    gst_number: {
      section: "kyc",
      priority: 21,
      type: "text",
      required: false,
      question: "GST registration number?",
      placeholder: "22AAAAA0000A1Z5",
    },

    rbi_registration_number: {
      section: "kyc",
      priority: 22,
      type: "text",
      required: false,
      question: "RBI / IRDAI / SEBI registration number (if applicable)?",
      placeholder: "e.g. RBI Ref no. / IRDAI Reg no.",
    },

    logo_url: {
      section: "kyc",
      priority: 23,
      type: "media_upload",
      required: false,
      question: "Upload your company logo.",
      max: 1,
    },

    kyc_documents: {
      section: "kyc",
      priority: 24,
      type: "media_upload",
      required: false,
      question: "Upload KYC / registration documents (PAN, GST, Cert of Incorporation).",
      max: 5,
    },
  },

  rules: [
    {
      fieldId: "max_loan_amount",
      when: {
        all: [
          { fieldId: "min_loan_amount", operator: "exists" },
          { fieldId: "max_loan_amount", operator: "exists" },
        ],
      },
      type: "validation",
      strategy: "gte",
      formula: "max_loan_amount >= min_loan_amount",
    },
    {
      fieldId: "interest_rate_max",
      when: {
        all: [
          { fieldId: "interest_rate_min", operator: "exists" },
          { fieldId: "interest_rate_max", operator: "exists" },
        ],
      },
      type: "validation",
      strategy: "gte",
      formula: "interest_rate_max >= interest_rate_min",
    },
    {
      fieldId: "max_tenure_years",
      when: {
        all: [
          { fieldId: "min_tenure_years", operator: "exists" },
          { fieldId: "max_tenure_years", operator: "exists" },
        ],
      },
      type: "validation",
      strategy: "gte",
      formula: "max_tenure_years >= min_tenure_years",
    },
  ],
} as unknown as PropertyFlowConfig;
