import type { PropertyFlowConfig } from "@/engines/types";

// ===== EXACT OPTIONS FROM EXCEL SHEET 7 - FINANCIAL REQUIREMENT =====

const REQUIREMENT_TYPES = [
  "Need Loan",
  "Need Investment",
  "Need Financial Partner",
  "Need Business Funding",
  "Need Mortgage",
  "Need Working Capital",
];

const CATEGORIES = [
  "Home Loan",
  "Property Loan",
  "Loan Against Property",
  "Plot Loan",
  "Construction Loan",
  "Business Loan",
  "Working Capital",
  "Builder Finance",
  "Developer Finance",
  "Hotel Finance",
  "Machinery Finance",
  "Agricultural Finance",
  "Private Finance",
  "Investment Funding",
];

const APPLICANT_TYPES = [
  "Individual",
  "Salaried Employee",
  "Self Employed",
  "Business Owner",
  "Agent",
  "Builder",
  "Developer",
  "Hotel Owner",
  "Farmer",
  "Startup",
];

const EMPLOYMENT_PROFILES = ["Salaried", "Self Employed", "Business Owner", "Startup Founder", "Farmer"];

const CREDIT_SCORES = ["750+", "700-750", "650-700", "Below 650", "Don't Know"];

const FINANCE_SOURCES = [
  "Bank",
  "NBFC",
  "Private Finance",
  "Investor",
  "Venture Capital",
  "Builder Finance",
  "Any Suitable Option",
];

const DOCUMENTS = ["Aadhaar", "PAN", "Salary Slip", "GST", "Property Documents", "Bank Statements"];

const ASSIGN_TO = ["Banks", "NBFCs", "Loan Agents", "Financial Advisors", "Private Financiers", "Investors"];

// ===== MAIN FINANCIAL REQUIREMENT FLOW =====

export const financialRequirementFlow = {
  id: "financial_requirement",

  category: "financial",

  label: "Financial Requirement",

  version: "v1-exact-match",

  engine: {
    mode: "dynamic_conversation",
    strictVisibilityResolution: true,
    dynamicQuestionResolver: true,
    reevaluateOnEveryAnswer: true,
    skipHiddenQuestions: true,
    clearHiddenFieldValues: true,
    preventDuplicateQuestions: true,
    removeIrrelevantQuestions: true,
    conversationMemory: true,
    smartConditionalFlow: true,
    supportContextualQuestions: true,
    supportAIExtraction: true,
    supportNaturalCorrections: true,
    supportConversationalAI: true,
    autoRevalidateDependencies: true,
    dynamicSectionActivation: true,
    clonePropertySupport: false,
    multiVariantSupport: false,
    preserveParentDataDuringClone: false,
    AIBasedNextQuestionSelection: true,
  },

  ai: {
    enabled: true,
    askOneQuestionAtATime: true,
    askOnlyRelevantQuestions: true,
    askOnlyMissingFields: true,
    supportGreetings: true,
    supportNaturalLanguage: true,
    supportCorrections: true,
    supportSkipIntent: true,
    supportIntentDetection: true,
    supportContextAwareness: true,
    supportConversationalMemory: true,
    supportDocumentExtraction: true,
    supportImageExtraction: true,
    supportAutoFill: true,
    supportDynamicFollowups: true,
    supportPriceCalculation: true,
    supportSmartSuggestions: true,
    supportHumanReplies: true,
    autoGenerateDescription: true,
    autoGenerateTitle: true,
    autoGenerateSEO: true,
  },

  sections: [
    {
      id: "financial_requirement",
      label: "Financial Requirement",
      priority: 1,
    },
  ],

  fields: {
    // ===== FIELD 1: EXAMPLE =====
    example_description: {
      section: "financial_requirement",
      priority: 1,
      type: "text",
      inputMode: "textarea",
      required: false,
      question:
        "Example: Looking for ₹75 Lakhs Home Loan for purchasing a ready-to-move apartment in Hyderabad. Salaried professional with good repayment history and documents ready",
      placeholder: "Describe your financial requirement in detail...",
    },

    // ===== FIELD 2: REQUIREMENT TYPE =====
    requirement_type: {
      section: "financial_requirement",
      priority: 2,
      type: "single_select",
      required: true,
      question: "Requirement Type:",
      options: REQUIREMENT_TYPES,
    },

    // ===== FIELD 3: CATEGORY =====
    category: {
      section: "financial_requirement",
      priority: 3,
      type: "single_select",
      required: true,
      question: "Category:",
      options: CATEGORIES,
    },

    // ===== FIELD 4: APPLICANT TYPE =====
    applicant_type: {
      section: "financial_requirement",
      priority: 4,
      type: "single_select",
      required: true,
      question: "Applicant Type:",
      options: APPLICANT_TYPES,
    },

    // ===== FIELD 5: PROPERTY INFORMATION =====
    property_information: {
      section: "financial_requirement",
      priority: 5,
      type: "text",
      inputMode: "textarea",
      required: false,
      question: "Property Information:",
      placeholder: "Text to type the information related to property involved in loan or business",
    },

    // ===== FIELD 6: REQUIRED AMOUNT =====
    required_amount: {
      section: "financial_requirement",
      priority: 6,
      type: "price",
      required: true,
      question: "Required Amount:",
    },

    // ===== FIELD 7: LOCATION =====
    location: {
      section: "financial_requirement",
      priority: 7,
      type: "smart_location",
      renderMode: "widget",
      widget: "SmartLocationWidget",
      required: true,
      question: "Location:",
      groupedFields: ["country", "state_name", "city", "locality", "sub_locality", "landmark", "address", "pincode"],
    },

    // ===== FIELD 8: EMPLOYMENT / BUSINESS PROFILE =====
    employment_business_profile: {
      section: "financial_requirement",
      priority: 8,
      type: "single_select",
      required: true,
      question: "Employment / Business Profile:",
      options: EMPLOYMENT_PROFILES,
    },

    // ===== FIELD 9: MONTHLY INCOME =====
    monthly_income: {
      section: "financial_requirement",
      priority: 9,
      type: "price",
      required: false,
      question: "Monthly Income:",
    },

    // ===== FIELD 10: ANNUAL INCOME =====
    annual_income: {
      section: "financial_requirement",
      priority: 10,
      type: "price",
      required: false,
      question: "Annual Income:",
    },

    // ===== FIELD 11: EXISTING EMI =====
    existing_emi: {
      section: "financial_requirement",
      priority: 11,
      type: "price",
      required: false,
      question: "Existing EMI:",
    },

    // ===== FIELD 12: CREDIT SCORE =====
    credit_score: {
      section: "financial_requirement",
      priority: 12,
      type: "single_select",
      required: true,
      question: "Credit Score:",
      options: CREDIT_SCORES,
    },

    // ===== FIELD 13: PREFERRED FINANCE SOURCE =====
    preferred_finance_source: {
      section: "financial_requirement",
      priority: 13,
      type: "single_select",
      required: true,
      question: "Preferred Finance Source:",
      options: FINANCE_SOURCES,
    },

    // ===== FIELD 14: UPLOAD DOCUMENTS =====
    upload_documents: {
      section: "financial_requirement",
      priority: 14,
      type: "multi_select",
      required: true,
      question: "Upload Documents:",
      options: DOCUMENTS,
    },

    // ===== FIELD 15: ASSIGN MY REQUIREMENT TO =====
    assign_my_requirement_to: {
      section: "financial_requirement",
      priority: 15,
      type: "multi_select",
      required: true,
      question: "Assign My Requirement To:",
      options: ASSIGN_TO,
    },
  },

  autoGeneration: {
    enabled: true,
    generateTitle: true,
    generateDescription: true,
    generateSEODescription: true,
    generateHighlights: true,
    generateTags: true,
    generatePropertySummary: true,
    triggerAfterFlowCompletion: true,
  },

  uploadSupport: {
    enabled: true,
    allowImages: true,
    allowPDFs: true,
    allowBrochures: true,
    autoExtractPropertyData: true,
    autoDetectPricing: true,
    autoDetectLocation: true,
    autoDetectAmenities: false,
    askOnlyMissingFieldsAfterExtraction: true,
  },

  submitFlow: {
    enabled: true,
    showPreviewBeforeSubmit: true,
    autoGenerateFinalSummary: true,
    showAIQualityScore: true,
    verifyRequiredFields: true,
  },

  rules: [
    { type: "dynamic_next_question" },
    { type: "skip_hidden_questions" },
    { type: "clear_hidden_values" },
    { type: "prevent_duplicate_questions" },
    { type: "dynamic_followup_questions" },
    { type: "recalculate_visibility_after_each_answer" },
    { type: "ask_only_relevant_questions" },
    { type: "smart_skip_logic" },
    { type: "auto_generate_description" },
  ],
};

export default financialRequirementFlow;
