import type { PropertyFlowConfig } from "@/engines/types";

const PLOT_TYPES = [
  "Residential Plot",
  "Villa Plot",
  "Farm Plot",
  "Commercial Plot",
  "Industrial Plot",
  "Layout Plot",
  "Corner Plot",
  "Open Land",
  "Lake View Plot",
  "Highway Facing Plot",
];

const PLOT_UNITS = ["Sq Ft", "Sq Yard", "Cent", "Gunta", "Acre", "Bigha"];

export const plotsFlow: PropertyFlowConfig = {
  id: "plots",

  category: "plots_land",

  label: "Plots & Land",

  version: "v2-client-aligned-plots",

  engine: {
    mode: "dynamic_conversation",

    strictVisibilityResolution: true,

    dynamicQuestionResolver: true,

    reevaluateOnEveryAnswer: true,

    skipHiddenQuestions: true,

    clearHiddenFieldValues: true,

    preventDuplicateQuestions: true,

    removeIrrelevantQuestions: true,

    conversationMemory: true,

    smartConditionalFlow: true,

    supportContextualQuestions: true,

    supportAIExtraction: true,

    supportNaturalCorrections: true,

    supportConversationalAI: true,

    autoRevalidateDependencies: true,

    dynamicSectionActivation: true,

    clonePropertySupport: true,

    multiVariantSupport: true,

    preserveParentDataDuringClone: true,

    AIBasedNextQuestionSelection: true,

    progressiveConversationMode: true,

    intelligentDependencyRouting: true,

    contextualSkipLogic: true,

    askOnlyContextualQuestions: true,

    propertyTypeAwareQuestions: true,

    dynamicFlowReordering: true,
  },

  ai: {
    enabled: true,

    askOneQuestionAtATime: true,

    askOnlyRelevantQuestions: true,

    askOnlyMissingFields: true,

    supportGreetings: true,

    supportNaturalLanguage: true,

    supportCorrections: true,

    supportSkipIntent: true,

    supportIntentDetection: true,

    supportContextAwareness: true,

    supportConversationalMemory: true,

    supportDocumentExtraction: true,

    supportImageExtraction: true,

    supportAutoFill: true,

    supportDynamicFollowups: true,

    supportPriceCalculation: true,

    supportSmartSuggestions: true,

    supportHumanReplies: true,

    autoGenerateDescription: true,

    autoGenerateTitle: true,

    autoGenerateSEO: true,

    supportVariantDetection: true,

    supportOptionalSectionSkipping: true,
  },

  sections: [
    {
      id: "basic_information",
      label: "Basic Information",
      priority: 1,
    },

    {
      id: "plot_configuration",
      label: "Plot Configuration",
      priority: 2,
    },

    {
      id: "pricing",
      label: "Pricing",
      priority: 3,
    },

    {
      id: "community",
      label: "Community Details",
      priority: 4,
    },

    {
      id: "features",
      label: "Features & Amenities",
      priority: 5,
    },

    {
      id: "legal",
      label: "Legal & Approvals",
      priority: 6,
    },

    {
      id: "location",
      label: "Location",
      priority: 7,
    },

    {
      id: "finalization",
      label: "Finalization",
      priority: 8,
    },
  ],

  fields: {
    plot_type: {
      section: "basic_information",

      priority: 1,

      type: "single_select",

      required: true,

      question: "What type of land are you listing?",

      options: PLOT_TYPES,
    },

    listed_by: {
      section: "basic_information",

      priority: 2,

      type: "single_select",

      required: true,

      question: "Who is listing this property?",

      options: ["Owner", "Agent", "Builder"],
    },

    listing_type: {
      section: "basic_information",

      priority: 3,

      type: "single_select",

      required: true,

      question: "Is this property for Buy, Rent or Lease?",

      options: ["Buy", "Rent", "Lease"],

      invalidateOnChange: ["total_price", "price_per_unit", "rent_amount"],
    },

    plot_size: {
      section: "plot_configuration",

      priority: 4,

      type: "measurement",

      required: true,

      requiredIfVisible: true,

      question: "What is the plot size?",

      units: PLOT_UNITS,

      aiFollowup: {
        triggerAfterAnswer: true,

        askForVariants: true,

        followupQuestion: "Do you have additional plot sizes available for separate listings?",
      },
    },

    add_multiple_plot_sizes: {
      section: "plot_configuration",

      priority: 5,

      type: "single_select",

      required: false,

      question: "Do you want to add multiple plot sizes?",

      options: ["Yes", "No"],
    },

    plot_variants: {
      section: "plot_configuration",

      priority: 6,

      type: "multi_variant_group",

      required: false,

      visibleIf: {
        field: "add_multiple_plot_sizes",
        equals: "Yes",
      },

      question: "Add all available plot size variants.",

      cloneStrategy: {
        enabled: true,

        preserveFields: [
          "plot_type",
          "listed_by",
          "listing_type",
          "facing",
          "road_width",
          "additional_features",
          "amenities",
          "approvals",
          "country",
          "state_name",
          "city",
          "locality",
          "sub_locality",
          "landmark",
          "address",
          "pincode",
          "property_highlights",
        ],

        editableFields: ["plot_size", "total_price", "price_per_unit", "rent_amount"],
      },
    },

    facing: {
      section: "plot_configuration",

      priority: 7,

      type: "single_select",

      required: false,

      question: "What is the plot facing?",

      options: ["East", "West", "North", "South", "North East", "North West", "South East", "South West"],
    },

    plot_measurements: {
      section: "plot_configuration",

      priority: 8,

      type: "plot_measurement_widget",

      required: false,

      question: "Please provide plot side measurements.",

      directions: [
        {
          id: "east_measurement",
          label: "East",
          unit: "Ft",
        },
        {
          id: "west_measurement",
          label: "West",
          unit: "Ft",
        },
        {
          id: "north_measurement",
          label: "North",
          unit: "Ft",
        },
        {
          id: "south_measurement",
          label: "South",
          unit: "Ft",
        },
      ],

      smartSuggestions: {
        enabled: true,

        examples: ["30 Ft", "40 Ft", "50 Ft", "60 Ft"],
      },

      renderMode: "interactive_widget",

      aiSuggestions: true,
      allowSkipGroup: true,
    },

    road_width: {
      section: "plot_configuration",

      priority: 9,

      type: "measurement",

      required: false,

      question: "What is the road width?",

      units: ["Ft"],
    },

    additional_features: {
      section: "plot_configuration",

      priority: 10,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "Which additional plot features are available?",

      options: [
        "Corner Plot",
        "Boundary Wall",
        "Fencing",
        "Water Connection",
        "Electricity Available",
        "Bore Available",
        "Cement Road",
        "BT Road",
        "Gravel Road",
        "Mud Road",
      ],
    },

    total_price: {
      section: "pricing",

      priority: 11,

      type: "price",

      required: false,

      visibleIf: {
        field: "listing_type",
        equals: "Buy",
      },

      question: "What is the total plot price?",

      smartSuggestions: {
        enabled: true,

        examples: ["25 Lakhs", "50 Lakhs", "1 Crore", "2.5 Crore"],
      },
    },

    price_per_unit: {
      section: "pricing",

      priority: 12,

      type: "price_per_unit",

      required: false,

      visibleIf: {
        field: "listing_type",
        equals: "Buy",
      },

      question: "What is the price per unit in SqFt?",

      dynamicUnitSource: {
        from: ["plot_size"],
      },

      autoCalculation: {
        enabled: true,

        calculate: "price_per_unit",

        formula: "Number(total_price) / Number((plot_size?.value))",
      },
    },

    rent_amount: {
      section: "pricing",

      priority: 13,

      type: "rental_price",

      required: false,

      visibleIf: {
        field: "listing_type",
        in: ["Rent", "Lease"],
      },

      question: "What is the monthly rental or lease amount?",
    },

    project_name: {
      section: "community",

      priority: 14,

      type: "text",

      required: false,

      question: "What is the community or project name?",
    },

    gated_community: {
      section: "community",

      priority: 15,

      type: "single_select",

      required: false,

      question: "Is this plot inside a gated community?",

      options: ["Yes", "No"],
    },

    total_plots: {
      section: "community",

      priority: 16,

      type: "number",

      required: false,

      visibleIf: {
        field: "gated_community",
        equals: "Yes",
      },

      question: "How many total plots are there in the project?",
    },

    total_project_area: {
      section: "community",

      priority: 17,

      type: "measurement",

      required: false,

      visibleIf: {
        field: "gated_community",
        equals: "Yes",
      },

      question: "What is the total project land area?",

      units: PLOT_UNITS,
    },

    amenities: {
      section: "features",

      priority: 18,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "Which amenities are available?",

      options: [
        "Gated Community",
        "Underground Drainage",
        "Street Lights",
        "Water Connection",
        "Electricity",
        "Avenue Plantation",
        "Black Top Roads",
        "Compound Wall",
        "Security",
        "Park",
        "Club House",
        "Parking",
        "Swimming Pool",
        "Gym",
        "Power Backup",
        "Children Play Area",
        "Garden",
      ],
    },

    payment_options: {
      section: "legal",

      priority: 19,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "What payment options are available?",

      options: [
        "Price Negotiable",
        "Bank Loan Available",
        "EMI Available",
        "Installments Available",
        "Flexible Payment Plan",
        "Investor Friendly",
        "NRI Assistance",
        "Immediate Registration",
      ],
    },

    approvals: {
      section: "legal",

      priority: 20,

      type: "multi_select",

      required: false,

      allowSkipGroup: true,

      question: "What approvals does this property have?",

      options: [
        "RERA Approved",
        "HMDA Approved",
        "DTCP Approved",
        "CRDA Approved",
        "Municipal Approved",
        "Panchayat Approved",
        "LP Number Available",
        "Approved Layout",
      ],
    },

    location: {
      section: "location",

      priority: 21,

      type: "smart_location",

      renderMode: "widget",

      widgetType: "smart_location",

      widget: "SmartLocationWidget",

      required: true,

      question: "Let's add the plot location details.",

      groupedFields: [
        "country",
        "state_name",
        "city",
        "locality",
        "sub_locality",
        "landmark",
        "address",
        "pincode",
        "google_maps_link",
        "latitude",
        "longitude",
      ],
    },

    property_highlights: {
      section: "finalization",

      priority: 22,

      type: "multi_select",

      required: false,

      maxSelections: 3,

      question: "Select up to 3 property highlights.",

      options: [
        "Verified Property",
        "RERA Approved",
        "High ROI",
        "Corner Property",
        "Investment Hotspot",
        "Future Growth Area",
        "Near Metro",
        "Gated Community",
        "Prime Location",
        "Lake View",
        "Highway Facing",
      ],
    },

    property_description: {
      section: "finalization",

      priority: 23,

      type: "ai_generated_text",

      required: false,

      aiGenerated: true,

      hiddenFromConversation: true,

      autoGenerateFrom: [
        "plot_type",
        "plot_size",
        "facing",
        "road_width",
        "approvals",
        "amenities",
        "location",
        "price_per_unit",
        "additional_features",
      ],
    },

    assign_nearest_agent: {
      section: "finalization",

      priority: 24,

      type: "single_select",

      required: false,

      question: "Do you want to assign this property to the nearest agent? Agent commission may apply.",

      options: ["Yes", "No"],
    },
  },

  autoGeneration: {
    enabled: true,

    generateTitle: true,

    generateDescription: true,

    generateSEODescription: true,

    generateHighlights: true,

    generateTags: true,

    generatePropertySummary: true,

    triggerAfterFlowCompletion: true,
  },

  uploadSupport: {
    enabled: true,

    allowImages: true,

    allowPDFs: true,

    allowBrochures: true,

    autoExtractPropertyData: true,

    autoDetectPricing: true,

    autoDetectLocation: true,

    autoDetectAmenities: true,

    askOnlyMissingFieldsAfterExtraction: true,
  },

  submitFlow: {
    enabled: true,

    showPreviewBeforeSubmit: true,

    autoGenerateFinalSummary: true,

    showAIQualityScore: true,

    verifyRequiredFields: true,
  },

  rules: [
    {
      type: "dynamic_next_question",
    },
    {
      type: "skip_hidden_questions",
    },
    {
      type: "clear_hidden_values",
    },
    {
      type: "prevent_duplicate_questions",
    },
    {
      type: "dynamic_followup_questions",
    },
    {
      type: "recalculate_visibility_after_each_answer",
    },
    {
      type: "ask_only_relevant_questions",
    },
    {
      type: "smart_skip_logic",
    },
    {
      type: "price_auto_calculation",
    },
    {
      type: "multi_variant_property_clone",
    },
    {
      type: "auto_generate_description",
    },
    {
      type: "plots_dependency_flow",
    },
  ],
};

export default plotsFlow;
