import type { PropertyFlowConfig } from "@/engines/types";

const APARTMENT_TYPES = [
  "Apartment / Flat",
  "Penthouse",
  "Studio Apartment",
  "Builder Floor Apartment",
  "Serviced Apartment",
];

const HOUSE_TYPES = [
  "Independent House",
  "Villa",
  "Duplex / Triplex",
  "Farm House",
  "Row House / Townhouse",
  "Gated Community House",
];

export const residentialFlow: PropertyFlowConfig = {
  category: "residential",

  label: "Residential",

  version: "v2-client-aligned-final",

  engine: {
    mode: "dynamic_conversation",
    strictVisibilityResolution: true,
    removeHiddenFieldsFromQueue: true,
    clearHiddenFieldValues: true,
    dynamicQuestionResolver: true,
    stateInvalidation: true,
    dependencyReevaluation: true,
    preventQuestionRepetition: true,
    autoCleanupInvalidState: true,
    maintainConversationMemory: true,
    allowNaturalCorrections: true,
    supportAIExtraction: true,
    conversationalPriorityMode: true,
  },

  questionResolver: {
    strategy: "dynamic_priority",
    skipHiddenFields: true,
    skipAnsweredFields: true,
    skipRejectedFields: true,
    reevaluateOnEveryAnswer: true,
    dynamicFollowups: true,
  },

  ai: {
    conversational: true,
    dynamicQuestioning: true,
    askOneQuestionAtATime: true,
    askOnlyMissingFields: true,
    allowNaturalConversation: true,
    supportGreetings: true,
    supportCorrections: true,
    supportTypos: true,
    supportIntentDetection: true,
    supportExtractionFromUploads: true,
    supportAutoFill: true,
    supportSmartSuggestions: true,
    supportHumanLikeReplies: true,
    supportContextAwareness: true,
    supportDynamicFollowups: true,
    persistSkippedFields: true,
    preventDuplicateQuestions: true,
    maintainConversationState: true,
    realtimeSuggestions: true,
    autoNormalizePricingUnits: true,
    supportQuickReplyChips: true,
    supportSearchableDropdowns: true,
    supportConversationRecovery: true,
    autoGenerateDescriptions: true,
    supportVisibilityRecalculation: true,
    supportDependencyTree: true,
    clearHiddenFieldValues: true,
    skipChildQuestionsOnParentSkip: true,
    recalculateFlowAfterEveryAnswer: true,
    preventIrrelevantQuestions: true,
    supportNaturalLanguageExtraction: true,
  },

  fields: {
    property_type: {
      priority: 1,
      type: "single_select",
      required: true,
      question: "What type of residential property are you listing?",
      options: [
        "Apartment / Flat",
        "Independent House",
        "Villa",
        "Duplex / Triplex",
        "Penthouse",
        "Row House / Townhouse",
        "Farm House",
        "Studio Apartment",
        "Serviced Apartment",
        "Builder Floor Apartment",
        "Gated Community House",
      ],
    },

    listed_by: {
      priority: 2,
      type: "single_select",
      required: true,
      question: "Who are you listing this property as?",
      options: ["Owner", "Agent", "Builder"],
    },

    listing_type: {
      priority: 3,
      type: "single_select",
      required: true,
      question: "Is this property for sale or rent?",
      options: ["Buy", "Rent"],
      invalidateOnChange: [
        "property_condition",
        "availability_status",
        "possession_date",
        "property_age",
        "available_from_date",
        "monthly_rent",
        "total_price",
      ],
    },

    property_condition: {
      priority: 4,
      type: "single_select",
      required: true,
      visibleIf: {
        field: "listing_type",
        equals: "Buy",
      },
      dependsOn: ["listing_type"],
      question: "What is the property condition?",
      options: ["New", "Resale"],
      invalidateOnChange: ["availability_status", "possession_date", "property_age"],
    },

    availability_status: {
      priority: 5,
      type: "single_select",
      required: false,
      visibleIf: {
        field: "property_condition",
        equals: "New",
      },
      dependsOn: ["property_condition"],
      question: "What is the availability status?",
      options: ["Ready to Move", "Under Construction"],
      invalidateOnChange: ["possession_date"],
    },

    possession_date: {
      priority: 6,
      type: "future_date",
      required: false,
      visibleIf: {
        field: "availability_status",
        equals: "Under Construction",
      },
      dependsOn: ["availability_status"],
      question: "When is possession expected?",
    },

    property_age: {
      priority: 7,
      type: "single_select",
      required: false,
      visibleIf: {
        field: "property_condition",
        equals: "Resale",
      },
      dependsOn: ["property_condition"],
      question: "What is the property age?",
      options: ["0-1 Years", "1-5 Years", "5-10 Years", "10+ Years"],
    },

    available_from_date: {
      priority: 8,
      type: "future_date",
      required: true,
      visibleIf: {
        field: "listing_type",
        equals: "Rent",
      },
      dependsOn: ["listing_type"],
      question: "When is the property available from?",
    },

    bhk_type: {
      priority: 9,
      type: "single_select",
      required: true,
      visibleIf: {
        field: "property_type",
        notEquals: "Studio Apartment",
      },
      question: "What is the bedroom configuration?",
      options: ["1 BHK", "2 BHK", "3 BHK", "4 BHK", "5 BHK", "6+ BHK"],
    },

    flat_size: {
      priority: 10,
      type: "measurement",
      required: true,
      visibleIf: {
        field: "property_type",
        in: APARTMENT_TYPES,
      },
      question: "What is the flat size?",
      units: ["Sq Ft"],
      variationGroup: {
        fields: ["flat_size", "total_price", "property_facing"],
      },
    },

    land_size: {
      priority: 11,
      type: "measurement",
      required: true,
      visibleIf: {
        field: "property_type",
        in: HOUSE_TYPES,
      },
      question: "What is the land size?",
      units: ["Sq Ft", "Sq Yard", "Cent", "Gunta", "Acre", "Bigha"],
      variationGroup: {
        fields: ["land_size", "built_area", "total_price", "property_facing"],
      },
    },

    built_area: {
      priority: 12,
      type: "measurement",
      required: true,
      visibleIf: {
        field: "property_type",
        in: HOUSE_TYPES,
      },
      question: "What is the built area?",
      units: ["Sq Ft"],
    },

    east_measurement: {
      priority: 13,
      type: "measurement",
      required: false,
      visibleIf: {
        field: "property_type",
        in: HOUSE_TYPES,
      },
      question: "What is the east side measurement?",
      units: ["Ft"],
    },

    west_measurement: {
      priority: 14,
      type: "measurement",
      required: false,
      visibleIf: {
        field: "property_type",
        in: HOUSE_TYPES,
      },
      question: "What is the west side measurement?",
      units: ["Ft"],
    },

    north_measurement: {
      priority: 15,
      type: "measurement",
      required: false,
      visibleIf: {
        field: "property_type",
        in: HOUSE_TYPES,
      },
      question: "What is the north side measurement?",
      units: ["Ft"],
    },

    south_measurement: {
      priority: 16,
      type: "measurement",
      required: false,
      visibleIf: {
        field: "property_type",
        in: HOUSE_TYPES,
      },
      question: "What is the south side measurement?",
      units: ["Ft"],
    },

    unit_type: {
      priority: 17,
      type: "measurement_unit",
      required: false,
      visibleIf: {
        field: "listing_type",
        equals: "Buy",
      },
      question: "Select pricing unit.",
      options: ["Sqft", "Sqyd", "Sqm", "Acre", "Gunta", "Cent", "Bigha"],
    },

    price_per_unit: {
      priority: 18,
      type: "price_per_unit",
      required: false,
      visibleIf: {
        field: "listing_type",
        equals: "Buy",
      },
      question: "What is the price per unit?",
    },

    total_price: {
      priority: 19,
      type: "price",
      required: true,
      visibleIf: {
        field: "listing_type",
        equals: "Buy",
      },
      question: "What is the total property price?",
    },

    monthly_rent: {
      priority: 20,
      type: "rental_price",
      required: true,
      visibleIf: {
        field: "listing_type",
        equals: "Rent",
      },
      question: "What is the monthly rent?",
    },

    bathroom_count: {
      priority: 21,
      type: "number",
      required: true,
      question: "How many bathrooms are available?",
      options: ["1", "2", "3+"],
    },

    balcony_count: {
      priority: 22,
      type: "number",
      required: false,
      visibleIf: {
        field: "property_type",
        in: [...APARTMENT_TYPES, "Villa", "Duplex / Triplex"],
      },
      question: "How many balconies are available?",
      options: ["1", "2", "3+"],
    },

    property_total_floors: {
      priority: 23,
      type: "number",
      required: false,
      visibleIf: {
        field: "property_type",
        in: HOUSE_TYPES,
      },
      question: "How many floors does the property have?",
    },

    total_floors: {
      priority: 24,
      type: "number",
      required: false,
      visibleIf: {
        field: "property_type",
        in: APARTMENT_TYPES,
      },
      question: "How many total floors are there in the building?",
    },

    floor_number: {
      priority: 25,
      type: "number",
      required: false,
      visibleIf: {
        field: "property_type",
        in: APARTMENT_TYPES,
      },
      question: "Which floor is the property on?",
    },

    parking_type: {
      priority: 26,
      type: "single_select",
      required: false,
      question: "What type of parking is available?",
      options: ["Covered Parking", "Open Parking", "Both", "No Parking"],
      invalidateOnChange: ["parking_count"],
    },

    parking_count: {
      priority: 27,
      type: "number",
      required: false,
      visibleIf: {
        field: "parking_type",
        in: ["Covered Parking", "Open Parking", "Both"],
      },
      dependsOn: ["parking_type"],
      question: "How many parking spaces are available?",
    },

    gated_community: {
      priority: 28,
      type: "single_select",
      required: false,
      question: "Is this inside a gated community?",
      options: ["Yes", "No"],
      invalidateOnChange: ["project_name", "total_towers", "floors_per_tower", "total_units", "project_land_area"],
    },

    project_name: {
      priority: 29,
      type: "text",
      required: false,
      visibleIf: {
        field: "gated_community",
        equals: "Yes",
      },
      dependsOn: ["gated_community"],
      question: "What is the project or community name?",
    },

    total_towers: {
      priority: 30,
      type: "number",
      required: false,
      visibleIf: {
        and: [
          {
            field: "gated_community",
            equals: "Yes",
          },
          {
            field: "property_type",
            in: APARTMENT_TYPES,
          },
        ],
      },
      dependsOn: ["gated_community"],
      question: "How many towers are in the project?",
    },

    floors_per_tower: {
      priority: 31,
      type: "number",
      required: false,
      visibleIf: {
        and: [
          {
            field: "gated_community",
            equals: "Yes",
          },
          {
            field: "property_type",
            in: APARTMENT_TYPES,
          },
        ],
      },
      dependsOn: ["total_towers"],
      question: "How many floors are there per tower?",
    },

    total_units: {
      priority: 32,
      type: "number",
      required: false,
      visibleIf: {
        and: [
          {
            field: "gated_community",
            equals: "Yes",
          },
          {
            field: "property_type",
            in: APARTMENT_TYPES,
          },
        ],
      },
      dependsOn: ["total_towers"],
      question: "How many total units are there?",
    },

    project_land_area: {
      priority: 33,
      type: "measurement",
      required: false,
      visibleIf: {
        and: [
          {
            field: "gated_community",
            equals: "Yes",
          },
          {
            field: "property_type",
            in: APARTMENT_TYPES,
          },
        ],
      },
      dependsOn: ["total_towers"],
      question: "What is the total project land area?",
      units: ["Acres", "Sq Yard", "Sq Ft"],
    },

    furnishing_status: {
      priority: 34,
      type: "single_select",
      required: true,
      question: "What is the furnishing status?",
      options: ["Unfurnished", "Semi Furnished", "Fully Furnished"],
      invalidateOnChange: ["furnishing_items"],
    },

    furnishing_items: {
      priority: 35,
      type: "multi_select",
      required: false,
      visibleIf: {
        field: "furnishing_status",
        in: ["Semi Furnished", "Fully Furnished"],
      },
      dependsOn: ["furnishing_status"],
      question: "What furnishing items are included?",
      options: ["AC", "Wardrobes", "Modular Kitchen", "Geysers", "Beds", "Sofa", "Dining Table", "TV"],
    },

    property_facing: {
      priority: 36,
      type: "single_select",
      required: true,
      question: "What is the property facing?",
      options: ["East", "West", "North", "South", "North East", "North West", "South East", "South West"],
    },

    amenities: {
      priority: 37,
      type: "multi_select",
      required: false,
      question: "What amenities are available?",
      options: [
        "Lift",
        "Parking",
        "Swimming Pool",
        "Gym",
        "Security",
        "Club House",
        "Power Backup",
        "Children Play Area",
        "Garden",
      ],
    },

    payment_options: {
      priority: 38,
      type: "multi_select",
      required: false,
      question: "What payment options are available?",
      options: [
        "Price Negotiable",
        "Bank Loan Available",
        "EMI Available",
        "Installments Available",
        "Flexible Payment Plan",
        "Construction Linked Payment",
        "Possession Linked Payment",
      ],
    },

    approvals: {
      priority: 39,
      type: "multi_select",
      required: false,
      question: "What approvals does this property have?",
      options: [
        "RERA Approved",
        "HMDA Approved",
        "DTCP Approved",
        "CRDA Approved",
        "Municipal Approved",
        "Panchayat Approved",
      ],
    },

    country: {
      priority: 40,
      type: "country",
      required: true,
      question: "Which country is the property located in?",
    },

    state: {
      priority: 41,
      type: "state",
      required: true,
      dependsOn: ["country"],
      question: "Which state is the property located in?",
    },

    city: {
      priority: 42,
      type: "city",
      required: true,
      dependsOn: ["state"],
      question: "Which city is the property located in?",
    },

    locality: {
      priority: 43,
      type: "locality",
      required: true,
      dependsOn: ["city"],
      question: "Which locality is the property located in?",
    },

    sub_locality: {
      priority: 44,
      type: "text",
      required: false,
      dependsOn: ["locality"],
      question: "Any sub locality or area name?",
    },

    landmark: {
      priority: 45,
      type: "text",
      required: false,
      dependsOn: ["locality"],
      question: "Any nearby landmark?",
    },

    full_address: {
      priority: 46,
      type: "textarea",
      required: true,
      question: "Please provide the full property address.",
    },

    pincode: {
      priority: 47,
      type: "pincode",
      required: true,
      dependsOn: ["city"],
      question: "What is the pincode?",
    },

    google_maps_link: {
      priority: 48,
      type: "url",
      required: false,
      question: "Please share Google Maps link if available.",
    },

    property_highlights: {
      priority: 49,
      type: "multi_select",
      required: false,
      maxSelections: 3,
      question: "Select up to 3 property highlights.",
      options: ["Verified Property", "Ready to Move", "Luxury Living", "Near Metro", "Investment Hotspot", "High ROI"],
    },

    property_description: {
      priority: 90,
      type: "ai_generated_text",
      required: false,
      question: "AI will generate the property description.",
      generation: {
        enabled: true,
        autoGenerate: true,
      },
    },

    media_uploads: {
      priority: 91,
      type: "media_upload",
      required: false,
      question: "Upload property images, videos, brochures or PDFs.",
      extraction: {
        enabled: true,
        autoExtractPropertyData: true,
        autoDetectMissingFields: true,
        continueFromExtractedState: true,
        multiFieldExtraction: true,
        confidenceScoring: true,
      },
    },

    contact_name: {
      priority: 99,
      type: "text",
      required: false,
      question: "Please share your name.",
    },

    mobile_number: {
      priority: 100,
      type: "phone",
      required: true,
      question: "Please share your mobile number.",
    },
  },

  rules: [
    {
      type: "normalize_pricing_units",
    },
    {
      type: "ask_only_missing_fields",
    },
    {
      type: "skip_hidden_fields",
    },
    {
      type: "clear_hidden_child_values",
    },
    {
      type: "prevent_duplicate_questions",
    },
    {
      type: "dynamic_followup_questions",
    },
    {
      type: "recalculate_visibility_after_each_answer",
    },
    {
      type: "auto_generate_description",
    },
  ],
};

export default residentialFlow;
