import type { PropertyFlowConfig } from "@/engines/types";

const APARTMENT_TYPES = [
  "Apartment / Flat",
  "Penthouse",
  "Studio Apartment",
  "Builder Floor Apartment",
  "Serviced Apartment",
];

const HOUSE_TYPES = [
  "Independent House",
  "Villa",
  "Duplex / Triplex",
  "Farm House",
  "Row House / Townhouse",
  "Gated Community House",
];

export const residentialFlow = {
  category: "residential",

  label: "Residential",

  version: "v5-client-clean-final",

  engine: {
    mode: "dynamic_conversation",

    strictVisibilityResolution: true,

    removeHiddenFieldsFromQueue: true,

    clearHiddenFieldValues: true,

    dynamicQuestionResolver: true,

    dependencyReevaluation: true,

    preventQuestionRepetition: true,

    autoCleanupInvalidState: true,

    maintainConversationMemory: true,

    allowNaturalCorrections: true,

    supportAIExtraction: true,

    conversationalPriorityMode: true,
  },

  questionResolver: {
    strategy: "dynamic_priority",

    skipHiddenFields: true,

    skipAnsweredFields: true,

    skipRejectedFields: true,

    reevaluateOnEveryAnswer: true,

    dynamicFollowups: true,
  },

  ai: {
    conversational: true,

    dynamicQuestioning: true,

    askOneQuestionAtATime: true,

    askOnlyMissingFields: true,

    allowNaturalConversation: true,

    supportGreetings: true,

    supportCorrections: true,

    supportTypos: true,

    supportIntentDetection: true,

    supportExtractionFromUploads: true,

    supportAutoFill: true,

    supportSmartSuggestions: true,

    supportHumanLikeReplies: true,

    supportContextAwareness: true,

    supportDynamicFollowups: true,

    preventDuplicateQuestions: true,

    maintainConversationState: true,

    realtimeSuggestions: true,

    autoNormalizePricingUnits: true,

    supportQuickReplyChips: true,

    supportSearchableDropdowns: true,

    supportConversationRecovery: true,

    autoGenerateDescriptions: true,
  },

  fields: {
    property_type: {
      priority: 1,

      type: "single_select",

      required: true,

      question: "What type of residential property are you listing?",

      options: [
        "Apartment / Flat",
        "Independent House",
        "Villa",
        "Duplex / Triplex",
        "Penthouse",
        "Row House / Townhouse",
        "Farm House",
        "Studio Apartment",
        "Serviced Apartment",
        "Builder Floor Apartment",
        "Gated Community House",
      ],

      suggestions: {
        enabled: true,

        chips: true,
      },
    },

    listed_by: {
      priority: 2,

      type: "single_select",

      required: true,

      question: "Who are you listing this property as?",

      options: ["Owner", "Agent", "Builder"],

      suggestions: {
        enabled: true,

        chips: true,
      },
    },

    listing_type: {
      priority: 3,

      type: "single_select",

      required: true,

      question: "Is this property for sale or rent?",

      options: ["Buy", "Rent"],

      suggestions: {
        enabled: true,

        chips: true,
      },

      invalidateOnChange: [
        "property_condition",
        "availability_status",
        "possession_date",
        "property_age",
        "available_from_date",
        "total_price",
        "monthly_rent",
      ],
    },

    property_condition: {
      priority: 4,

      type: "single_select",

      required: true,

      visibleIf: {
        field: "listing_type",
        equals: "Buy",
      },

      dependsOn: ["listing_type"],

      question: "What is the property condition?",

      options: ["New", "Resale"],

      suggestions: {
        enabled: true,

        chips: true,
      },

      invalidateOnChange: ["availability_status", "possession_date", "property_age"],
    },

    availability_status: {
      priority: 5,

      type: "single_select",

      required: false,

      visibleIf: {
        field: "property_condition",
        equals: "New",
      },

      dependsOn: ["property_condition"],

      question: "What is the availability status?",

      options: ["Ready", "Under Construction"],

      suggestions: {
        enabled: true,

        chips: true,
      },

      invalidateOnChange: ["possession_date"],
    },

    possession_date: {
      priority: 6,

      type: "future_date",

      required: false,

      visibleIf: {
        field: "availability_status",
        equals: "Under Construction",
      },

      dependsOn: ["availability_status"],

      question: "When is possession expected?",
    },

    property_age: {
      priority: 7,

      type: "single_select",

      required: false,

      visibleIf: {
        field: "property_condition",
        equals: "Resale",
      },

      dependsOn: ["property_condition"],

      question: "What is the property age?",

      options: ["0-1 Years", "1-5 Years", "5-10 Years", "10+ Years"],

      suggestions: {
        enabled: true,

        chips: true,
      },
    },

    available_from_date: {
      priority: 8,

      type: "future_date",

      required: true,

      visibleIf: {
        field: "listing_type",
        equals: "Rent",
      },

      dependsOn: ["listing_type"],

      question: "When is the property available from?",
    },

    bhk_type: {
      priority: 9,

      type: "single_select",

      required: true,

      visibleIf: {
        field: "property_type",
        notEquals: "Studio Apartment",
      },

      dependsOn: ["property_type"],

      question: "What is the bedroom configuration?",

      options: ["1 BHK", "2 BHK", "3 BHK", "4 BHK", "5 BHK", "6+ BHK"],

      suggestions: {
        enabled: true,

        chips: true,
      },
    },

    flat_size: {
      priority: 10,

      type: "measurement",

      required: true,

      visibleIf: {
        field: "property_type",
        in: APARTMENT_TYPES,
      },

      dependsOn: ["property_type"],

      question: "What is the flat size?",

      units: ["Sq Ft"],

      smartSuggestions: {
        enabled: true,

        examples: ["1200 Sq Ft", "1500 Sq Ft", "1800 Sq Ft"],
      },
    },

    land_size: {
      priority: 11,

      type: "measurement",

      required: true,

      visibleIf: {
        field: "property_type",
        in: HOUSE_TYPES,
      },

      dependsOn: ["property_type"],

      question: "What is the land size?",

      units: ["Sq Ft", "Sq Yard", "Cent", "Gunta", "Acre"],
    },

    built_area: {
      priority: 12,

      type: "measurement",

      required: true,

      visibleIf: {
        field: "property_type",
        in: HOUSE_TYPES,
      },

      dependsOn: ["property_type"],

      question: "What is the built area?",

      units: ["Sq Ft"],
    },

    total_price: {
      priority: 13,

      type: "price",

      required: true,

      visibleIf: {
        field: "listing_type",
        equals: "Buy",
      },

      dependsOn: ["listing_type"],

      question: "What is the total property price?",

      smartSuggestions: {
        enabled: true,

        examples: ["75 Lakhs", "1.2 Crore", "2 Crore"],
      },
    },

    monthly_rent: {
      priority: 14,

      type: "rental_price",

      required: true,

      visibleIf: {
        field: "listing_type",
        equals: "Rent",
      },

      dependsOn: ["listing_type"],

      question: "What is the monthly rent?",

      smartSuggestions: {
        enabled: true,

        examples: ["15000", "25000", "50000"],
      },
    },

    bathroom_count: {
      priority: 15,

      type: "number",

      required: true,

      question: "How many bathrooms are available?",
    },

    balcony_count: {
      priority: 16,

      type: "number",

      required: false,

      visibleIf: {
        field: "property_type",
        in: [...APARTMENT_TYPES, "Villa", "Duplex / Triplex"],
      },

      question: "How many balconies are available?",
    },

    floor_number: {
      priority: 17,

      type: "number",

      required: false,

      visibleIf: {
        field: "property_type",
        in: APARTMENT_TYPES,
      },

      question: "Which floor is the property on?",
    },

    total_floors: {
      priority: 18,

      type: "number",

      required: false,

      visibleIf: {
        field: "property_type",
        in: APARTMENT_TYPES,
      },

      question: "How many total floors are there in the building?",
    },

    parking_type: {
      priority: 19,

      type: "single_select",

      required: false,

      question: "What type of parking is available?",

      options: ["Covered Parking", "Open Parking", "Both", "No Parking"],

      suggestions: {
        enabled: true,

        chips: true,
      },

      invalidateOnChange: ["parking_count"],
    },

    parking_count: {
      priority: 20,

      type: "number",

      required: false,

      visibleIf: {
        field: "parking_type",
        in: ["Covered Parking", "Open Parking", "Both"],
      },

      dependsOn: ["parking_type"],

      question: "How many parking spaces are available?",
    },

    gated_community: {
      priority: 21,

      type: "single_select",

      required: false,

      question: "Is this inside a gated community?",

      options: ["Yes", "No"],

      suggestions: {
        enabled: true,

        chips: true,
      },

      invalidateOnChange: ["project_name", "total_towers", "floors_per_tower", "total_units"],
    },

    project_name: {
      priority: 22,

      type: "text",

      required: false,

      visibleIf: {
        field: "gated_community",
        equals: "Yes",
      },

      dependsOn: ["gated_community"],

      question: "What is the project or community name?",
    },

    total_towers: {
      priority: 23,

      type: "number",

      required: false,

      visibleIf: {
        and: [
          {
            field: "gated_community",
            equals: "Yes",
          },
          {
            field: "property_type",
            in: APARTMENT_TYPES,
          },
        ],
      },

      question: "How many towers are in the project?",
    },

    floors_per_tower: {
      priority: 24,

      type: "number",

      required: false,

      visibleIf: {
        and: [
          {
            field: "gated_community",
            equals: "Yes",
          },
          {
            field: "property_type",
            in: APARTMENT_TYPES,
          },
        ],
      },

      question: "How many floors are there per tower?",
    },

    total_units: {
      priority: 25,

      type: "number",

      required: false,

      visibleIf: {
        and: [
          {
            field: "gated_community",
            equals: "Yes",
          },
          {
            field: "property_type",
            in: APARTMENT_TYPES,
          },
        ],
      },

      question: "How many total units are there?",
    },

    furnishing_status: {
      priority: 26,

      type: "single_select",

      required: true,

      question: "What is the furnishing status?",

      options: ["Unfurnished", "Semi Furnished", "Fully Furnished"],

      suggestions: {
        enabled: true,

        chips: true,
      },

      invalidateOnChange: ["furnishing_items"],
    },

    furnishing_items: {
      priority: 27,

      type: "multi_select",

      required: false,

      visibleIf: {
        field: "furnishing_status",
        in: ["Semi Furnished", "Fully Furnished"],
      },

      dependsOn: ["furnishing_status"],

      question: "What furnishing items are included?",

      options: ["AC", "Wardrobes", "Modular Kitchen", "Geysers", "Beds", "Sofa", "Dining Table", "TV"],
    },

    property_facing: {
      priority: 28,

      type: "single_select",

      required: true,

      question: "What is the property facing?",

      options: ["East", "West", "North", "South", "North East", "North West", "South East", "South West"],

      suggestions: {
        enabled: true,

        chips: true,
      },
    },

    amenities: {
      priority: 29,

      type: "multi_select",

      required: false,

      question: "What amenities are available?",

      options: [
        "Lift",
        "Swimming Pool",
        "Gym",
        "Security",
        "Club House",
        "Power Backup",
        "Children Play Area",
        "Parking",
      ],
    },

    approvals: {
      priority: 30,

      type: "multi_select",

      required: false,

      question: "What approvals does this property have?",

      options: ["RERA Approved", "HMDA Approved", "DTCP Approved", "Municipal Approved", "Bank Approved"],
    },

    location: {
      priority: 31,

      type: "smart_location",

      required: true,

      question: "Where is the property located?",

      smartLocation: {
        autoDetectCountry: true,

        autoDetectState: true,

        autoDetectCity: true,

        autoDetectLocality: true,

        enableGoogleMapsSelection: true,

        enableSearchSuggestions: true,

        allowMapPinSelection: true,

        autofillHierarchy: true,

        showPopularSuggestions: true,
      },

      smartSuggestions: {
        enabled: true,

        examples: ["Gachibowli Hyderabad", "Kondapur Hyderabad", "Madhapur Hyderabad"],
      },
    },

    property_highlights: {
      priority: 32,

      type: "multi_select",

      required: false,

      maxSelections: 3,

      question: "Select up to 3 property highlights.",

      options: ["Verified Property", "Ready to Move", "Luxury Living", "Near Metro", "Investment Hotspot", "High ROI"],
    },
  },

  autoGeneration: {
    enabled: true,

    generateTitle: true,

    generateDescription: true,

    generateSEODescription: true,

    generateHighlights: true,

    triggerAfterFlowCompletion: true,
  },

  uploadSupport: {
    enabled: true,

    allowImages: true,

    allowPDFs: true,

    allowBrochures: true,

    autoExtractPropertyData: true,

    askOnlyMissingFieldsAfterExtraction: true,
  },

  submitFlow: {
    enabled: true,

    showPreviewBeforeSubmit: true,

    autoGenerateFinalSummary: true,
  },

  rules: [
    {
      type: "normalize_pricing_units",
    },
    {
      type: "ask_only_missing_fields",
    },
    {
      type: "skip_hidden_fields",
    },
    {
      type: "clear_hidden_child_values",
    },
    {
      type: "prevent_duplicate_questions",
    },
    {
      type: "dynamic_followup_questions",
    },
    {
      type: "recalculate_visibility_after_each_answer",
    },
    {
      type: "auto_generate_description",
    },
  ],
};

export default residentialFlow;
