import type { PropertyFlowConfig } from "@/engines/types";

const APARTMENT_TYPES = [
  "Apartment / Flat",
  "Penthouse",
  "Studio Apartment",
  "Builder Floor Apartment",
  "Serviced Apartment",
];

const HOUSE_TYPES = [
  "Independent House",
  "Villa",
  "Duplex / Triplex",
  "Farm House",
  "Row House / Townhouse",
  "Gated Community House",
];

export const residentialFlow = {
  id: "residential",

  category: "residential",

  label: "Residential",

  version: "v10-client-ai-dynamic-final",

  engine: {
    mode: "dynamic_conversation",

    strictVisibilityResolution: true,

    dynamicQuestionResolver: true,

    reevaluateOnEveryAnswer: true,

    skipHiddenQuestions: true,

    clearHiddenFieldValues: true,

    preventDuplicateQuestions: true,

    removeIrrelevantQuestions: true,

    conversationMemory: true,

    smartConditionalFlow: true,

    supportContextualQuestions: true,

    supportAIExtraction: true,

    supportNaturalCorrections: true,

    supportConversationalAI: true,

    autoRevalidateDependencies: true,

    dynamicSectionActivation: true,

    clonePropertySupport: true,

    multiVariantSupport: true,

    preserveParentDataDuringClone: true,

    AIBasedNextQuestionSelection: true,
  },

  ai: {
    enabled: true,

    askOneQuestionAtATime: true,

    askOnlyRelevantQuestions: true,

    askOnlyMissingFields: true,

    supportGreetings: true,

    supportNaturalLanguage: true,

    supportCorrections: true,

    supportSkipIntent: true,

    supportIntentDetection: true,

    supportContextAwareness: true,

    supportConversationalMemory: true,

    supportDocumentExtraction: true,

    supportImageExtraction: true,

    supportAutoFill: true,

    supportDynamicFollowups: true,

    supportPriceCalculation: true,

    supportSmartSuggestions: true,

    supportHumanReplies: true,

    autoGenerateDescription: true,

    autoGenerateTitle: true,

    autoGenerateSEO: true,
  },

  sections: [
    {
      id: "basic_information",

      label: "Basic Information",

      priority: 1,
    },

    {
      id: "property_configuration",

      label: "Property Configuration",

      priority: 2,
    },

    {
      id: "pricing",

      label: "Pricing",

      priority: 3,
    },

    {
      id: "project_information",

      label: "Project Information",

      priority: 4,
    },

    {
      id: "features",

      label: "Features & Amenities",

      priority: 5,
    },

    {
      id: "location",

      label: "Location",

      priority: 6,
    },

    {
      id: "legal",

      label: "Legal & Approvals",

      priority: 7,
    },
  ],

  fields: {
    property_type: {
      section: "basic_information",

      priority: 1,

      type: "single_select",

      required: true,

      question: "What type of residential property are you listing?",

      options: [
        "Apartment / Flat",
        "Independent House",
        "Villa",
        "Duplex / Triplex",
        "Penthouse",
        "Row House / Townhouse",
        "Farm House",
        "Studio Apartment",
        "Serviced Apartment",
        "Builder Floor Apartment",
        "Gated Community House",
      ],
    },

    listed_by: {
      section: "basic_information",

      priority: 2,

      type: "single_select",

      required: true,

      question: "Who is listing this property?",

      options: ["Owner", "Agent", "Builder"],
    },

    listing_type: {
      section: "basic_information",

      priority: 3,

      type: "single_select",

      required: true,

      question: "Do you want to Sell or Rent this property?",

      options: ["Buy", "Rent"],

      invalidateOnChange: [
        "property_condition",
        "availability_status",
        "possession_date",
        "property_age",
        "available_from_date",
        "monthly_rent",
        "total_price",
      ],
    },

    property_condition: {
      section: "basic_information",

      priority: 4,

      type: "single_select",

      required: true,

      visibleIf: {
        field: "listing_type",
        equals: "Buy",
      },

      question: "Is this property New or Resale?",

      options: ["New", "Resale"],
    },

    availability_status: {
      section: "basic_information",

      priority: 5,

      type: "single_select",

      required: false,

      visibleIf: {
        and: [
          {
            field: "listing_type",
            equals: "Buy",
          },
          {
            field: "property_condition",
            equals: "New",
          },
        ],
      },

      question: "What is the availability status?",

      options: ["Ready to Move", "Under Construction"],
    },

    possession_date: {
      section: "basic_information",

      priority: 6,

      type: "future_date",
      renderAs: "calendar",

      required: false,

      visibleIf: {
        field: "availability_status",
        equals: "Under Construction",
      },

      question: "When is possession expected?",
    },

    property_age: {
      section: "basic_information",

      priority: 7,

      type: "single_select",

      required: false,

      visibleIf: {
        field: "property_condition",
        equals: "Resale",
      },

      question: "What is the property age?",

      options: ["0-1 Years", "1-5 Years", "5-10 Years", "10+ Years"],
    },

    available_from_date: {
      section: "basic_information",

      priority: 8,

      type: "future_date",
      renderAs: "calendar",

      required: true,

      visibleIf: {
        field: "listing_type",
        equals: "Rent",
      },

      question: "When is the property available from?",
    },

    bhk_type: {
      section: "property_configuration",

      priority: 9,

      type: "text",

      required: true,

      visibleIf: {
        field: "property_type",
        notEquals: "Studio Apartment",
      },

      question: "What is the BHK type?",
    },

    flat_size: {
      section: "property_configuration",

      priority: 10,

      type: "measurement",

      required: true,

      visibleIf: {
        field: "property_type",
        in: APARTMENT_TYPES,
      },

      question: "What is the flat size?",

      units: ["Sq Ft"],
    },

    add_multiple_sizes: {
      section: "property_configuration",

      priority: 11,

      type: "single_select",

      required: false,

      visibleIf: {
        field: "listed_by",
        equals: "Builder",
      },

      question: "Do you want to add multiple flat sizes for this project?",

      options: ["Yes", "No"],
    },

    flat_variants: {
      section: "property_configuration",

      priority: 12,

      type: "multi_variant_group",

      required: false,

      visibleIf: {
        field: "add_multiple_sizes",
        equals: "Yes",
      },

      question: "Add all available flat variants.",

      cloneStrategy: {
        enabled: true,

        preserveFields: [
          "property_type",
          "listed_by",
          "listing_type",
          "project_name",
          "gated_community",
          "country",
          "state_name",
          "city",
          "locality",
          "sub_locality",
          "landmark",
          "address",
          "pincode",
          "amenities",
          "approvals",
          "property_highlights",
        ],

        editableFields: ["flat_size", "total_price", "floor_number", "property_facing", "availability_status"],
      },
    },

    land_size: {
      section: "property_configuration",

      priority: 13,

      type: "measurement",

      required: true,

      visibleIf: {
        field: "property_type",
        in: HOUSE_TYPES,
      },

      question: "What is the land size?",

      units: ["Sq Ft", "Sq Yard", "Cent", "Gunta", "Acre"],
    },

    built_area: {
      section: "property_configuration",

      priority: 14,

      type: "measurement",

      required: true,

      visibleIf: {
        field: "property_type",
        in: HOUSE_TYPES,
      },

      question: "What is the built area?",

      units: ["Sq Ft"],
    },

    plot_side_measurements: {
      section: "property_configuration",

      priority: 15,

      type: "plot_measurement_widget",

      renderMode: "widget",

      required: false,

      visibleIf: {
        field: "property_type",
        in: HOUSE_TYPES,
      },

      question: "Please provide plot side measurements.",

      units: ["Ft"],
    },

    price_per_unit: {
      section: "pricing",

      priority: 16,

      type: "text",

      inputMode: "price_with_unit",

      required: false,

      visibleIf: {
        field: "listing_type",
        equals: "Buy",
      },

      question: "What is the price per Sq Ft / Sq Yard?",

      autoCalculation: {
        enabled: true,

        calculate: "total_price",

        formula: "flat_size * price_per_unit",
      },
    },

    total_price: {
      section: "pricing",

      priority: 17,

      type: "price",

      required: true,

      visibleIf: {
        field: "listing_type",
        equals: "Buy",
      },

      question: "What is the total property price?",

      smartSuggestions: {
        enabled: true,

        examples: ["75 Lakhs", "1 Crore", "2.5 Crore"],
      },
    },

    monthly_rent: {
      section: "pricing",

      priority: 18,

      type: "rental_price",

      required: true,

      visibleIf: {
        field: "listing_type",
        equals: "Rent",
      },

      question: "What is the monthly rent amount?",
    },

    bathroom_count: {
      section: "property_configuration",

      priority: 19,

      type: "number",

      required: true,

      visibleIf: {
        field: "bhk_type",
        exists: true,
      },

      question: "How many bathrooms are available?",
    },

    balcony_count: {
      section: "property_configuration",

      priority: 20,

      type: "number",

      required: false,

      visibleIf: {
        and: [
          {
            field: "property_type",
            in: [...APARTMENT_TYPES, "Villa", "Duplex / Triplex"],
          },
          {
            field: "bhk_type",
            notEquals: "1 RK",
          },
        ],
      },

      question: "How many balconies are available?",
    },

    floor_number: {
      section: "property_configuration",

      priority: 21,

      type: "number",

      required: false,

      visibleIf: {
        field: "property_type",
        in: APARTMENT_TYPES,
      },

      question: "Which floor is the property on?",
    },

    total_floors: {
      section: "property_configuration",

      priority: 22,

      type: "number",

      required: false,

      visibleIf: {
        field: "property_type",
        in: APARTMENT_TYPES,
      },

      question: "How many total floors are there?",
    },

    gated_community: {
      section: "project_information",

      priority: 23,

      type: "single_select",

      required: false,

      question: "Is this property inside a gated community?",

      options: ["Yes", "No"],

      invalidateOnChange: ["project_name", "total_towers", "floors_per_tower", "total_units", "total_land_area"],
    },

    project_name: {
      section: "project_information",

      priority: 24,

      type: "text",

      required: false,

      visibleIf: {
        field: "gated_community",
        equals: "Yes",
      },

      question: "What is the project name?",
    },

    total_towers: {
      section: "project_information",

      priority: 25,

      type: "number",

      required: false,

      visibleIf: {
        and: [
          {
            field: "gated_community",
            equals: "Yes",
          },
          {
            field: "property_type",
            in: APARTMENT_TYPES,
          },
        ],
      },

      question: "How many towers are there in the project?",
    },

    floors_per_tower: {
      section: "project_information",

      priority: 26,

      type: "number",

      required: false,

      visibleIf: {
        and: [
          {
            field: "gated_community",
            equals: "Yes",
          },
          {
            field: "property_type",
            in: APARTMENT_TYPES,
          },
          {
            field: "total_towers",
            exists: true,
          },
        ],
      },

      question: "How many floors are there per tower?",
    },

    total_units: {
      section: "project_information",

      priority: 27,

      type: "number",

      required: false,

      visibleIf: {
        and: [
          {
            field: "gated_community",
            equals: "Yes",
          },
          {
            field: "total_towers",
            exists: true,
          },
          {
            field: "property_type",
            in: APARTMENT_TYPES,
          },
        ],
      },

      question: "How many total units are available in the project?",
    },

    total_land_area: {
      section: "project_information",

      priority: 28,

      type: "measurement",

      required: false,

      visibleIf: {
        field: "gated_community",
        equals: "Yes",
      },

      question: "What is the total project land area?",

      units: ["Acre", "Sq Yard", "Sq Ft"],
    },

    furnishing_status: {
      section: "features",

      priority: 29,

      type: "single_select",

      required: true,

      question: "What is the furnishing status?",

      options: ["Unfurnished", "Semi Furnished", "Fully Furnished"],
    },

    furnishing_items: {
      section: "features",

      priority: 30,

      type: "multi_select",

      required: false,

      visibleIf: {
        field: "furnishing_status",
        in: ["Semi Furnished", "Fully Furnished"],
      },

      question: "Which furnishing items are included?",

      options: ["AC", "Wardrobes", "Modular Kitchen", "Beds", "Sofa", "TV", "Dining Table", "Geysers"],
    },

    property_facing: {
      section: "features",

      priority: 31,

      type: "single_select",

      required: false,
      
      allowSkip: true,

      question: "What is the property facing?",

      options: ["East", "West", "North", "South", "North East", "North West", "South East", "South West"],
    },

    amenities: {
      section: "features",

      priority: 32,

      type: "multi_select",

      required: false,

      question: "Which amenities are available?",

      options: [
        "Lift",
        "Swimming Pool",
        "Gym",
        "Security",
        "Club House",
        "Power Backup",
        "Children Play Area",
        "Parking",
        "Walking Track",
        "Indoor Games",
      ],
    },

    payment_options: {
      section: "legal",

      priority: 33,

      type: "multi_select",

      required: false,

      question: "What payment options are available?",

      options: [
        "Bank Loan Available",
        "Price Negotiable",
        "EMI Available",
        "Installments Available",
        "Flexible Payment Plan",
        "Construction Linked Payment",
        "Possession Linked Payment",
        "Zero Down Payment",
        "Low Booking Amount",
        "Assured Rental Returns",
        "Investor Friendly",
        "NRI Assistance",
        "Pre-EMI Support",
        "Premium Bank Tie-Ups",
        "Custom Payment Plans",
        "Immediate Registration",
      ],
    },

    approvals: {
      section: "legal",

      priority: 34,

      type: "multi_select",

      required: false,

      question: "What approvals does this property have?",

      options: [
        "RERA Approved",
        "HMDA Approved",
        "DTCP Approved",
        "CRDA Approved",
        "Municipal Approved",
        "Panchayat Approved",
        "LP Number Available",
        "Approved Layout",
      ],
    },

    location: {
      section: "location",

      priority: 35,

      type: "smart_location",

      renderMode: "widget",

      widget: "SmartLocationWidget",

      required: true,

      question: "Let's add the property location details.",

      groupedFields: ["country", "state_name", "city", "locality", "sub_locality", "landmark", "address", "pincode"],
    },

    property_highlights: {
      section: "features",

      priority: 36,

      type: "multi_select",

      required: false,

      maxSelections: 3,

      question: "Select up to 3 property highlights.",

      options: [
        "Verified Property",
        "Verified Owner",
        "Trusted Agent",
        "Bank Approved",
        "RERA Approved",
        "Approved Layout",
        "Clear Title",
        "Price Drop",
        "Best Deal",
        "Limited Offer",
        "Negotiable",
        "Low Booking Amount",
        "Zero Down Payment",
        "EMI Available",
        "Popular",
        "Trending",
        "Most Viewed",
        "By Owner",
        "By Agent",
        "By Builder",
        "Hot Property",
        "Premium Listing",
        "Featured",
        "Ready to Move",
        "Under Construction",
        "New Launch",
        "Immediate Possession",
        "Newly Renovated",
        "Investment Hotspot",
        "High ROI",
        "Rental Income",
        "Future Growth Area",
        "Investor Friendly",
        "Gated Community",
        "Luxury Living",
        "Family Friendly",
        "Near Metro",
        "Nature View",
        "Corner Property",
        "Fully Furnished",
        "Semi Furnished",
        "Bachelor Friendly",
        "Family Preferred",
        "Pet Friendly",
      ],
    },

    assign_nearest_agent: {
      section: "basic_information",

      priority: 37,

      type: "single_select",

      required: false,

      question: "Do you want to assign the nearest agent?",

      options: ["Yes", "No"],
    },
  },

  autoGeneration: {
    enabled: true,

    generateTitle: true,

    generateDescription: true,

    generateSEODescription: true,

    generateHighlights: true,

    generateTags: true,

    generatePropertySummary: true,

    triggerAfterFlowCompletion: true,
  },

  uploadSupport: {
    enabled: true,

    allowImages: true,

    allowPDFs: true,

    allowBrochures: true,

    autoExtractPropertyData: true,

    autoDetectPricing: true,

    autoDetectLocation: true,

    autoDetectAmenities: true,

    askOnlyMissingFieldsAfterExtraction: true,
  },

  submitFlow: {
    enabled: true,

    showPreviewBeforeSubmit: true,

    autoGenerateFinalSummary: true,

    showAIQualityScore: true,

    verifyRequiredFields: true,
  },

  rules: [
    {
      type: "dynamic_next_question",
    },
    {
      type: "skip_hidden_questions",
    },
    {
      type: "clear_hidden_values",
    },
    {
      type: "prevent_duplicate_questions",
    },
    {
      type: "dynamic_followup_questions",
    },
    {
      type: "recalculate_visibility_after_each_answer",
    },
    {
      type: "ask_only_relevant_questions",
    },
    {
      type: "smart_skip_logic",
    },
    {
      type: "price_auto_calculation",
    },
    {
      type: "multi_variant_property_clone",
    },
    {
      type: "auto_generate_description",
    },
  ],
};

export default residentialFlow;
