
ALTER TABLE public.builder_profiles
  ADD COLUMN IF NOT EXISTS project_subtitle text,
  ADD COLUMN IF NOT EXISTS project_location text,
  ADD COLUMN IF NOT EXISTS hero_image text,
  ADD COLUMN IF NOT EXISTS bhk_types_offered text,
  ADD COLUMN IF NOT EXISTS size_range text,
  ADD COLUMN IF NOT EXISTS land_area text,
  ADD COLUMN IF NOT EXISTS total_units_count integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_floors_count text,
  ADD COLUMN IF NOT EXISTS towers_count integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS clubhouse_description text,
  ADD COLUMN IF NOT EXISTS clubhouse_images text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS master_plan_image text,
  ADD COLUMN IF NOT EXISTS floor_plans_data jsonb DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS gallery_images text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS latitude double precision,
  ADD COLUMN IF NOT EXISTS longitude double precision,
  ADD COLUMN IF NOT EXISTS google_maps_link text,
  ADD COLUMN IF NOT EXISTS brochure_url text,
  ADD COLUMN IF NOT EXISTS timeline_data jsonb DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS live_stats_data jsonb DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS about_features text[] DEFAULT '{}'::text[],
  ADD COLUMN IF NOT EXISTS amenity_images jsonb DEFAULT '[]';
