
INSERT INTO public.nl_interview_packs
  (code, title, description, goal_codes, estimated_minutes, is_active, metadata)
VALUES
  ('nl_core_v1',
   'Return To Roots — Core Interview',
   'A warm, adaptive conversation that helps our AI companion understand who you are, how you live, and what you truly want from natural living.',
   ARRAY[]::text[],
   6,
   true,
   jsonb_build_object('version', 1, 'sections',
     jsonb_build_array('warmup','lifestyle','experience','commitment','vision','wrapup')))
ON CONFLICT (code) DO UPDATE SET
  title = EXCLUDED.title, description = EXCLUDED.description,
  estimated_minutes = EXCLUDED.estimated_minutes, is_active = true,
  metadata = EXCLUDED.metadata, updated_at = now();

INSERT INTO public.nl_ai_profile_fields (code, label, description, field_type, category, sort_order, is_active, metadata)
VALUES
  ('profession',            'Profession',              'Primary work or income source.',                     'text',   'lifestyle',   10, true, '{}'::jsonb),
  ('lifestyle_pace',        'Lifestyle Pace',          'How fast or slow their day-to-day life is.',         'enum',   'lifestyle',   20, true, jsonb_build_object('options', jsonb_build_array('very_slow','slow','balanced','busy','very_busy'))),
  ('family_situation',      'Family Situation',        'Who they''re considering natural living with.',      'text',   'lifestyle',   30, true, '{}'::jsonb),
  ('farming_experience',    'Farming Experience',      'Self-reported hands-on farming background.',         'enum',   'experience',  40, true, jsonb_build_object('options', jsonb_build_array('none','beginner','some','experienced','expert'))),
  ('time_availability',     'Time Availability',       'How much time they can realistically give.',         'enum',   'commitment',  50, true, jsonb_build_object('options', jsonb_build_array('few_hours_month','weekends','evenings_weekends','part_time','full_time'))),
  ('involvement_style',     'Involvement Style',       'Hands-on vs. managed involvement preference.',       'enum',   'commitment',  55, true, jsonb_build_object('options', jsonb_build_array('hands_on','shared','mostly_managed','fully_managed'))),
  ('budget_range',          'Budget Range',            'Approximate investable amount in INR lakhs.',        'enum',   'commitment',  60, true, jsonb_build_object('options', jsonb_build_array('under_10L','10L_25L','25L_50L','50L_1Cr','1Cr_3Cr','above_3Cr'))),
  ('preferred_location',    'Preferred Location',      'Region, state, or drive-time from a city.',          'text',   'lifestyle',   70, true, '{}'::jsonb),
  ('timeline_horizon',      'Timeline Horizon',        'When they plan to move / start.',                    'enum',   'commitment',  80, true, jsonb_build_object('options', jsonb_build_array('exploring','within_6m','within_1y','within_2y','long_term'))),
  ('revenue_expectation',   'Revenue Expectation',     'Do they expect income from the land?',               'enum',   'vision',      90, true, jsonb_build_object('options', jsonb_build_array('no_income','some_offset','meaningful_income','primary_income'))),
  ('land_size_preference',  'Land Size Preference',    'Approximate acreage they''re considering.',          'enum',   'vision',     100, true, jsonb_build_object('options', jsonb_build_array('under_1_acre','1_3_acres','3_5_acres','5_10_acres','10_plus_acres'))),
  ('sustainability_focus',  'Sustainability Focus',    'Ecological / regenerative priorities.',              'multi',  'vision',     110, true, jsonb_build_object('options', jsonb_build_array('regenerative_soil','water_conservation','biodiversity','renewable_energy','food_forest','waste_zero'))),
  ('wellness_focus',        'Wellness Focus',          'Health / retreat priorities.',                       'multi',  'vision',     120, true, jsonb_build_object('options', jsonb_build_array('mental_calm','physical_health','spiritual','family_bonding','digital_detox','yoga_ayurveda'))),
  ('community_preference',  'Community Preference',    'How communal vs. private they want life.',           'enum',   'lifestyle',  130, true, jsonb_build_object('options', jsonb_build_array('solo','family_only','close_friends','small_community','large_community'))),
  ('risk_tolerance',        'Risk Tolerance',          'Appetite for uncertainty in the venture.',           'scale',  'commitment', 140, true, jsonb_build_object('min',1,'max',5)),
  ('motivation_core',       'Core Motivation',         'The emotional / narrative "why" in their words.',    'text',   'vision',     150, true, '{}'::jsonb),
  ('off_grid_readiness',    'Off-Grid Readiness',      'Comfort with self-sufficient living.',               'enum',   'experience', 160, true, jsonb_build_object('options', jsonb_build_array('need_full_utilities','partial_off_grid','fully_off_grid_ready'))),
  ('water_priority',        'Water Access Priority',   'How important assured water access is.',             'scale',  'commitment', 170, true, jsonb_build_object('min',1,'max',5)),
  ('name_preferred',        'Preferred Name',          'How they''d like our AI companion to address them.', 'text',   'warmup',       5, true, '{}'::jsonb)
ON CONFLICT (code) DO UPDATE SET
  label = EXCLUDED.label, description = EXCLUDED.description,
  field_type = EXCLUDED.field_type, category = EXCLUDED.category,
  sort_order = EXCLUDED.sort_order, is_active = true,
  metadata = EXCLUDED.metadata, updated_at = now();

WITH pack AS (SELECT id FROM public.nl_interview_packs WHERE code = 'nl_core_v1')
INSERT INTO public.nl_question_bank
  (code, pack_id, question, helper_text, question_type, options, applies_when, weight, category, sort_order, is_required, is_active, tags, metadata)
SELECT q.code, (SELECT id FROM pack), q.question, q.helper_text, q.question_type, q.options, q.applies_when, q.weight, q.category, q.sort_order, q.is_required, true, q.tags, q.metadata
FROM (VALUES
  ('nl_q_name',
   'Before we begin — what should I call you?',
   'Whatever feels most natural. First name is perfect.',
   'text', '{}'::jsonb, '{}'::jsonb, 1.0, 'warmup', 10, false,
   ARRAY['warmup'],
   jsonb_build_object('field_code','name_preferred','suggestions', jsonb_build_array())),

  ('nl_q_motivation',
   'What is drawing you toward natural living right now?',
   'A sentence or two in your own words. There''s no wrong answer.',
   'text', '{}'::jsonb, '{}'::jsonb, 1.5, 'warmup', 20, true,
   ARRAY['warmup','motivation'],
   jsonb_build_object('field_code','motivation_core','suggestions',
     jsonb_build_array('A calmer, slower life','Growing my own food','Legacy for family','A break from the city','Health & wellness'))),

  ('nl_q_profession',
   'What do you do today for work?',
   'A short label is fine — "software engineer", "family business", "retired teacher".',
   'text', '{}'::jsonb, '{}'::jsonb, 1.0, 'lifestyle', 30, false,
   ARRAY['lifestyle'],
   jsonb_build_object('field_code','profession','suggestions',
     jsonb_build_array('Corporate professional','Business owner','Doctor / healthcare','Retired','Homemaker','Creative / freelance'))),

  ('nl_q_pace',
   'How would you describe the pace of your life these days?',
   NULL,
   'single_choice',
   jsonb_build_array(
     jsonb_build_object('value','very_slow','label','Quiet and slow'),
     jsonb_build_object('value','slow','label','Fairly relaxed'),
     jsonb_build_object('value','balanced','label','Balanced'),
     jsonb_build_object('value','busy','label','Busy most days'),
     jsonb_build_object('value','very_busy','label','Always on')),
   '{}'::jsonb, 1.0, 'lifestyle', 40, true,
   ARRAY['lifestyle'],
   jsonb_build_object('field_code','lifestyle_pace')),

  ('nl_q_family',
   'Who are you imagining this natural-living life with?',
   'Solo, partner, kids, extended family — whatever feels true.',
   'text', '{}'::jsonb, '{}'::jsonb, 0.8, 'lifestyle', 50, false,
   ARRAY['lifestyle'],
   jsonb_build_object('field_code','family_situation','suggestions',
     jsonb_build_array('Just me','With my partner','With young kids','Multi-generational family','Close friends / community'))),

  ('nl_q_community',
   'And how communal or private would you like it to feel?',
   NULL,
   'single_choice',
   jsonb_build_array(
     jsonb_build_object('value','solo','label','Very private, mostly solo'),
     jsonb_build_object('value','family_only','label','Family only'),
     jsonb_build_object('value','close_friends','label','A small circle of friends'),
     jsonb_build_object('value','small_community','label','A small community'),
     jsonb_build_object('value','large_community','label','A larger, vibrant community')),
   '{}'::jsonb, 0.9, 'lifestyle', 60, false,
   ARRAY['lifestyle'],
   jsonb_build_object('field_code','community_preference')),

  ('nl_q_location',
   'Any part of India — or drive-time from a city — you have in mind?',
   'It''s okay to be vague. "Near Bangalore, 2 hours out" works.',
   'text', '{}'::jsonb, '{}'::jsonb, 1.2, 'lifestyle', 70, true,
   ARRAY['location'],
   jsonb_build_object('field_code','preferred_location','suggestions',
     jsonb_build_array('Near Bangalore','Near Hyderabad','Near Mumbai / Pune','Kerala backwaters','Himalayan foothills','Open to suggestions'))),

  ('nl_q_farming_exp',
   'How much hands-on farming or gardening have you done before?',
   NULL,
   'single_choice',
   jsonb_build_array(
     jsonb_build_object('value','none','label','None yet'),
     jsonb_build_object('value','beginner','label','A little — plants, balcony, kitchen garden'),
     jsonb_build_object('value','some','label','Some — small plot or seasonal farming'),
     jsonb_build_object('value','experienced','label','Experienced hands'),
     jsonb_build_object('value','expert','label','I''ve run land before')),
   '{}'::jsonb, 1.2, 'experience', 80, true,
   ARRAY['experience'],
   jsonb_build_object('field_code','farming_experience')),

  ('nl_q_off_grid',
   'How ready are you for off-grid living — bore water, solar, no easy delivery?',
   'Honest is best. Most people start somewhere in the middle.',
   'single_choice',
   jsonb_build_array(
     jsonb_build_object('value','need_full_utilities','label','I need city-like utilities'),
     jsonb_build_object('value','partial_off_grid','label','Partial off-grid is fine'),
     jsonb_build_object('value','fully_off_grid_ready','label','Fully off-grid — bring it on')),
   jsonb_build_object('not_answers', jsonb_build_object('lifestyle_pace', jsonb_build_array('very_busy'))),
   0.9, 'experience', 90, false,
   ARRAY['experience'],
   jsonb_build_object('field_code','off_grid_readiness')),

  ('nl_q_time',
   'Realistically, how much time can you give to this in a typical month?',
   NULL,
   'single_choice',
   jsonb_build_array(
     jsonb_build_object('value','few_hours_month','label','A few hours a month'),
     jsonb_build_object('value','weekends','label','Occasional weekends'),
     jsonb_build_object('value','evenings_weekends','label','Evenings and weekends'),
     jsonb_build_object('value','part_time','label','Part-time — a few days a week'),
     jsonb_build_object('value','full_time','label','Full-time / moving there')),
   '{}'::jsonb, 1.3, 'commitment', 100, true,
   ARRAY['commitment'],
   jsonb_build_object('field_code','time_availability')),

  ('nl_q_involvement',
   'And how hands-on do you want to be with the day-to-day work?',
   NULL,
   'single_choice',
   jsonb_build_array(
     jsonb_build_object('value','hands_on','label','Fully hands-on'),
     jsonb_build_object('value','shared','label','Shared — I''ll do part'),
     jsonb_build_object('value','mostly_managed','label','Mostly managed for me'),
     jsonb_build_object('value','fully_managed','label','Fully managed — I want passive')),
   '{}'::jsonb, 1.2, 'commitment', 110, true,
   ARRAY['commitment'],
   jsonb_build_object('field_code','involvement_style')),

  ('nl_q_budget',
   'And what budget range are you comfortable exploring?',
   'This just helps us show you land that''s realistic for you.',
   'single_choice',
   jsonb_build_array(
     jsonb_build_object('value','under_10L','label','Under ₹10L'),
     jsonb_build_object('value','10L_25L','label','₹10L – ₹25L'),
     jsonb_build_object('value','25L_50L','label','₹25L – ₹50L'),
     jsonb_build_object('value','50L_1Cr','label','₹50L – ₹1Cr'),
     jsonb_build_object('value','1Cr_3Cr','label','₹1Cr – ₹3Cr'),
     jsonb_build_object('value','above_3Cr','label','Above ₹3Cr')),
   '{}'::jsonb, 1.4, 'commitment', 120, true,
   ARRAY['commitment','budget'],
   jsonb_build_object('field_code','budget_range')),

  ('nl_q_timeline',
   'When do you imagine actually starting?',
   NULL,
   'single_choice',
   jsonb_build_array(
     jsonb_build_object('value','exploring','label','Just exploring for now'),
     jsonb_build_object('value','within_6m','label','Within 6 months'),
     jsonb_build_object('value','within_1y','label','Within a year'),
     jsonb_build_object('value','within_2y','label','1–2 years out'),
     jsonb_build_object('value','long_term','label','It''s a long-term dream')),
   '{}'::jsonb, 1.1, 'commitment', 130, true,
   ARRAY['commitment'],
   jsonb_build_object('field_code','timeline_horizon')),

  ('nl_q_water',
   'How important is assured water access on the land?',
   '1 = not a concern · 5 = absolute must',
   'scale',
   jsonb_build_object('min',1,'max',5),
   jsonb_build_object('not_answers', jsonb_build_object('farming_experience', jsonb_build_array('none'))),
   0.9, 'commitment', 140, false,
   ARRAY['commitment'],
   jsonb_build_object('field_code','water_priority')),

  ('nl_q_risk',
   'And how comfortable are you with uncertainty in the early years?',
   '1 = I want it predictable · 5 = I love a real adventure',
   'scale',
   jsonb_build_object('min',1,'max',5),
   '{}'::jsonb, 0.8, 'commitment', 150, false,
   ARRAY['commitment'],
   jsonb_build_object('field_code','risk_tolerance')),

  ('nl_q_land_size',
   'What size of land feels right for what you have in mind?',
   NULL,
   'single_choice',
   jsonb_build_array(
     jsonb_build_object('value','under_1_acre','label','Under 1 acre'),
     jsonb_build_object('value','1_3_acres','label','1 – 3 acres'),
     jsonb_build_object('value','3_5_acres','label','3 – 5 acres'),
     jsonb_build_object('value','5_10_acres','label','5 – 10 acres'),
     jsonb_build_object('value','10_plus_acres','label','10+ acres')),
   '{}'::jsonb, 1.0, 'vision', 160, true,
   ARRAY['vision'],
   jsonb_build_object('field_code','land_size_preference')),

  ('nl_q_revenue',
   'Do you expect the land to generate income, or is that not the point?',
   NULL,
   'single_choice',
   jsonb_build_array(
     jsonb_build_object('value','no_income','label','No — it''s for me / us'),
     jsonb_build_object('value','some_offset','label','A little — offset costs'),
     jsonb_build_object('value','meaningful_income','label','Yes — meaningful income'),
     jsonb_build_object('value','primary_income','label','Yes — primary income')),
   '{}'::jsonb, 1.1, 'vision', 170, true,
   ARRAY['vision','revenue'],
   jsonb_build_object('field_code','revenue_expectation')),

  ('nl_q_sustainability',
   'Which sustainability threads matter most to you?',
   'Choose any that resonate — even one is fine.',
   'multi_choice',
   jsonb_build_array(
     jsonb_build_object('value','regenerative_soil','label','Regenerative soil'),
     jsonb_build_object('value','water_conservation','label','Water conservation'),
     jsonb_build_object('value','biodiversity','label','Biodiversity'),
     jsonb_build_object('value','renewable_energy','label','Renewable energy'),
     jsonb_build_object('value','food_forest','label','Food forest / permaculture'),
     jsonb_build_object('value','waste_zero','label','Zero-waste living')),
   jsonb_build_object('goals_any',
     jsonb_build_array('return_to_farming','homesteading','food_forest','carbon_conservation','community_living','organic_produce_business','school_farm')),
   1.0, 'vision', 180, false,
   ARRAY['vision','sustainability'],
   jsonb_build_object('field_code','sustainability_focus')),

  ('nl_q_wellness',
   'And on the wellness side — what would you love the land to give you?',
   NULL,
   'multi_choice',
   jsonb_build_array(
     jsonb_build_object('value','mental_calm','label','Mental calm'),
     jsonb_build_object('value','physical_health','label','Physical health'),
     jsonb_build_object('value','spiritual','label','Spiritual practice'),
     jsonb_build_object('value','family_bonding','label','Family bonding'),
     jsonb_build_object('value','digital_detox','label','Digital detox'),
     jsonb_build_object('value','yoga_ayurveda','label','Yoga & Ayurveda')),
   jsonb_build_object('goals_any',
     jsonb_build_array('wellness_retreat','weekend_farmhouse','retirement_living','spiritual_ashram','community_living')),
   0.9, 'vision', 190, false,
   ARRAY['vision','wellness'],
   jsonb_build_object('field_code','wellness_focus'))
) AS q(code, question, helper_text, question_type, options, applies_when, weight, category, sort_order, is_required, tags, metadata)
ON CONFLICT (code) DO UPDATE SET
  pack_id = EXCLUDED.pack_id, question = EXCLUDED.question,
  helper_text = EXCLUDED.helper_text, question_type = EXCLUDED.question_type,
  options = EXCLUDED.options, applies_when = EXCLUDED.applies_when,
  weight = EXCLUDED.weight, category = EXCLUDED.category,
  sort_order = EXCLUDED.sort_order, is_required = EXCLUDED.is_required,
  is_active = true, tags = EXCLUDED.tags, metadata = EXCLUDED.metadata, updated_at = now();
