// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smyypmthspsrvwydzsxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNteXlwbXRoc3BzcnZ3eWR6c3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MjY0ODUsImV4cCI6MjA3ODIwMjQ4NX0.QRGxSOW7aEG0b3wXAtEEojJlB1B0V6BZZtUJYpHQsDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});